My Application: MeshBuilder Class Reference
MeshBuilder Class Reference
Provides methods to generate mesh of different shapes.
#include <MeshBuilder.h>
Static Public Member Functions
static Mesh * GenerateAxes (const std::string &meshName, float lengthX, float lengthY, float lengthZ)
Generate the vertices of a reference Axes; Use red for x-axis, green for y-axis, blue for z-axis Then generate the VBO/IBO and store them in Mesh object.
static Mesh * GenerateQuad (const std::string &meshName, Color color, TexCoord _texCoord)
Generate the vertices of a quad; Use random color for each vertex Then generate the VBO/IBO and store them in Mesh object.
static Mesh * GenerateCube (const std::string &meshName, Color color)
Generate the vertices of a cube; Use random color for each vertex Then generate the VBO/IBO and store them in Mesh object.
static Mesh * GenerateCircle (const std::string &meshName, Color color, int radius)
static Mesh * GenerateRing (const std::string &meshName, Color color, int iRadius, int oRadius)
static Mesh * GenerateSphere (const std::string &meshName, Color color, double radius, bool hemisphere=false)
static Mesh * GenerateCylinder (const std::string &meshName, Color color, double radius, double height, bool hemicylinder=false)
static Mesh * GenerateTorus (const std::string &meshName, Color color, unsigned int numStack, unsigned int numSlice, float oRadius, float iRadius)
Generate the vertices of a torus; Use color for each vertex Then generate the VBO/IBO and store them in Mesh object.
static Mesh * GenerateCone (const std::string &meshName, Color color, double radius, double height)
Generate the vertices of a cone; Use color for each vertex Then generate the VBO/IBO and store them in Mesh object.
static Mesh * GenerateOBJ (const std::string &meshName, const std::string &file_path)
static Mesh * GenerateText (const std::string &meshName, unsigned numRow, unsigned numCol)
Detailed Description
Provides methods to generate mesh of different shapes.
Class MeshBuilder:
Definition at line 24 of file MeshBuilder.h.
Member Function Documentation
Mesh * MeshBuilder::GenerateAxes (const std::string & meshName, float lengthX, float lengthY, float lengthZ) static
Generate the vertices of a reference Axes; Use red for x-axis, green for y-axis, blue for z-axis Then generate the VBO/IBO and store them in Mesh object.
Parameters
meshName - name of mesh
lengthX - x-axis should start at -lengthX / 2 and end at lengthX / 2
lengthY - y-axis should start at -lengthY / 2 and end at lengthY / 2
lengthZ - z-axis should start at -lengthZ / 2 and end at lengthZ / 2
Returns
Pointer to mesh storing VBO/IBO of reference axes
Definition at line 18 of file MeshBuilder.cpp.
References Vertex::color, Mesh::DRAW_LINES, Mesh::indexBuffer, Mesh::indexSize, Mesh::mode, Vertex::pos, Position::Set(), and Mesh::vertexBuffer.
Referenced by SP2::Init().
Mesh * MeshBuilder::GenerateCircle (const std::string & meshName, Color color, int radius) static
Definition at line 324 of file MeshBuilder.cpp.
References Vertex::color, Math::DegreeToRadian(), Mesh::DRAW_TRIANGLE_STRIP, Mesh::indexBuffer, Mesh::indexSize, Mesh::mode, Vertex::normal, Vertex::pos, Vector3::Set(), Position::Set(), and Mesh::vertexBuffer.
Mesh * MeshBuilder::GenerateCone (const std::string & meshName, Color color, double radius, double height) static
Generate the vertices of a cone; Use color for each vertex Then generate the VBO/IBO and store them in Mesh object.
Parameters
meshName - name of mesh
color - color of mesh
radius - radius of cone
height - height of cone
Returns
Pointer to mesh storing VBO/IBO of cube
Definition at line 610 of file MeshBuilder.cpp.
References Vertex::color, Math::DegreeToRadian(), Mesh::DRAW_TRIANGLE_STRIP, Mesh::indexBuffer, Mesh::indexSize, Mesh::mode, Vertex::normal, Vector3::Normalize(), Vertex::pos, Vector3::Set(), Position::Set(), and Mesh::vertexBuffer.
Mesh * MeshBuilder::GenerateCube (const std::string & meshName, Color color) static
Generate the vertices of a cube; Use random color for each vertex Then generate the VBO/IBO and store them in Mesh object.
Parameters
meshName - name of mesh
lengthX - width of cube
lengthY - height of cube
lengthZ - depth of cube
Returns
Pointer to mesh storing VBO/IBO of cube
Definition at line 135 of file MeshBuilder.cpp.
References Vertex::color, Mesh::DRAW_TRIANGLES, Mesh::indexBuffer, Mesh::indexSize, Mesh::mode, Vertex::normal, Vertex::pos, Vector3::Set(), Position::Set(), and Mesh::vertexBuffer.
Mesh * MeshBuilder::GenerateCylinder (const std::string & meshName, Color color, double radius, double height, bool hemicylinder = false) static
Definition at line 462 of file MeshBuilder.cpp.
References Vertex::color, Math::DegreeToRadian(), Mesh::DRAW_TRIANGLE_STRIP, Mesh::indexBuffer, Mesh::indexSize, Mesh::mode, Vertex::normal, Vertex::pos, Vector3::Set(), Position::Set(), and Mesh::vertexBuffer.
Mesh * MeshBuilder::GenerateOBJ (const std::string & meshName, const std::string & file_path) static
Definition at line 649 of file MeshBuilder.cpp.
References Mesh::DRAW_TRIANGLES, Mesh::indexBuffer, Mesh::indexSize, IndexVBO(), LoadOBJ(), Mesh::mode, and Mesh::vertexBuffer.
Referenced by SP2::Init(), SP2::initCabinet(), SP2::initCamera(), SP2::initCar(), SP2::initGame(), SP2::initHands(), SP2::initHuman(), SP2::initItems(), SP2::initPatch(), SP2::initSpecialItems(), and SP2::initSuperMarket().
Mesh * MeshBuilder::GenerateQuad (const std::string & meshName, Color color, TexCoord _texCoord) static
Generate the vertices of a quad; Use random color for each vertex Then generate the VBO/IBO and store them in Mesh object.
Parameters
meshName - name of mesh
lengthX - width of quad
lengthY - height of quad
Returns
Pointer to mesh storing VBO/IBO of quad
Definition at line 74 of file MeshBuilder.cpp.
References Vertex::color, Mesh::DRAW_TRIANGLES, Mesh::indexBuffer, Mesh::indexSize, Mesh::mode, Vertex::normal, Vertex::pos, TexCoord::Set(), Vector3::Set(), Position::Set(), Vertex::texCoord, TexCoord::u, TexCoord::v, and Mesh::vertexBuffer.
Referenced by SP2::initCar(), SP2::initItems(), SP2::initMap(), and SP2::initOuterSkybox().
Mesh * MeshBuilder::GenerateRing (const std::string & meshName, Color color, int iRadius, int oRadius) static
Definition at line 361 of file MeshBuilder.cpp.
References Vertex::color, Math::DegreeToRadian(), Mesh::DRAW_TRIANGLE_STRIP, Mesh::indexBuffer, Mesh::indexSize, Mesh::mode, Vertex::normal, Vertex::pos, Vector3::Set(), Position::Set(), and Mesh::vertexBuffer.
Mesh * MeshBuilder::GenerateSphere (const std::string & meshName, Color color, double radius, bool hemisphere = false) static
Definition at line 398 of file MeshBuilder.cpp.
References Vertex::color, Math::DegreeToRadian(), Mesh::DRAW_TRIANGLE_STRIP, Mesh::indexBuffer, Mesh::indexSize, Mesh::mode, Vertex::normal, Vertex::pos, Vector3::Set(), Position::Set(), and Mesh::vertexBuffer.
Mesh * MeshBuilder::GenerateText (const std::string & meshName, unsigned numRow, unsigned numCol) static
Definition at line 678 of file MeshBuilder.cpp.
References Mesh::DRAW_TRIANGLES, Mesh::indexBuffer, Mesh::indexSize, Mesh::mode, Vertex::pos, TexCoord::Set(), Position::Set(), Vertex::texCoord, and Mesh::vertexBuffer.
Referenced by SP2::Init().
Mesh * MeshBuilder::GenerateTorus (const std::string & meshName, Color color, unsigned int numStack, unsigned int numSlice, float oRadius, float iRadius) static
Generate the vertices of a torus; Use color for each vertex Then generate the VBO/IBO and store them in Mesh object.
Parameters
meshName - name of mesh
color - color of mesh
numStack - number of stacks for torus
numSlice - number of slices for torus
iRadius - Inner radius of torus
oRadius - Outer radius of torus
Returns
Pointer to mesh storing VBO/IBO of cube
Definition at line 548 of file MeshBuilder.cpp.
References Vertex::color, Math::DegreeToRadian(), Mesh::DRAW_TRIANGLE_STRIP, Mesh::indexBuffer, Mesh::indexSize, Mesh::mode, Vertex::normal, Vector3::Normalize(), Vertex::pos, Vector3::Set(), Position::Set(), and Mesh::vertexBuffer.
The documentation for this class was generated from the following files:
MyGraphics/Source/MeshBuilder.h
MyGraphics/Source/MeshBuilder.cpp