My Application: CTrolley Class Reference
CTrolley Class Reference
Defines the functions for Trolley.cpp.
#include <Trolley.h>
Public Member Functions
CTrolley (void)
CTrolley default constructor.
CTrolley (int _ID, Vector3 _translate, Vector3 _rotate, Vector3 _scale, Vector3 _size)
CTrolley overloaded constructor.
virtual ~CTrolley (void)
CTrolley destructor.
void setCamera ()
Set camera for trolley during init stage.
void updatePosition ()
Update trolley's position based on where the new camera position is.
virtual void calcBound ()
Calculate bound with translate, size and scale.
Public Member Functions inherited from CObj
CObj (void)
Default constructor.
CObj (int _ID, Vector3 _translate, Vector3 _rotate, Vector3 _scale, Vector3 _size)
Overloaded constructor.
Vector3 getTranslate ()
return translate values
Vector3 getRotate ()
return rotate values
Vector3 getScale ()
return scale values
Vector3 getMaxBound ()
return maxBound values
Vector3 getMinBound ()
return minBound values
Vector3 getSize ()
return size values
int getID ()
return ID
bool getRender ()
return render state
void setRender (bool _render)
set render state
void setRotateY (float _rotateY)
set rotation on y axis
void setTranslateX (float _translateX)
set rotation on x axis
void setTranslate (Vector3 _translate)
set translation
virtual ~CObj (void)
Destructor.
Data Fields
Camera3 camera
std::vector< CItem * > itemList
Additional Inherited Members
Protected Attributes inherited from CObj
int ID
Vector3 translate
Vector3 rotate
Vector3 scale
Vector3 maxBound
Vector3 minBound
Vector3 size
bool render
Detailed Description
Defines the functions for Trolley.cpp.
Class Trolley:
Definition at line 25 of file Trolley.h.
Constructor & Destructor Documentation
CTrolley::CTrolley (void)
CTrolley default constructor.
Definition at line 9 of file Trolley.cpp.
CTrolley::CTrolley (int _ID, Vector3 _translate, Vector3 _rotate, Vector3 _scale, Vector3 _size)
CTrolley overloaded constructor.
Definition at line 19 of file Trolley.cpp.
CTrolley::~CTrolley (void) virtual
CTrolley destructor.
Definition at line 29 of file Trolley.cpp.
Member Function Documentation
void CTrolley::calcBound () virtual
Calculate bound with translate, size and scale.
Reimplemented from CObj.
Definition at line 69 of file Trolley.cpp.
References CObj::maxBound, CObj::minBound, CObj::scale, Vector3::Set(), CObj::size, CObj::translate, Vector3::x, Vector3::y, and Vector3::z.
void CTrolley::setCamera ()
Set camera for trolley during init stage.
Definition at line 39 of file Trolley.cpp.
References camera, Vector3::Normalized(), Camera::position, CObj::scale, CObj::size, Camera::target, CObj::translate, Camera::up, Vector3::y, and Vector3::z.
void CTrolley::updatePosition ()
Update trolley's position based on where the new camera position is.
Definition at line 54 of file Trolley.cpp.
References camera, Camera::position, CObj::scale, CObj::size, Camera::target, CObj::translate, Vector3::y, and Vector3::z.
Referenced by Camera3::Update().
Field Documentation
Camera3 CTrolley::camera
Definition at line 34 of file Trolley.h.
Referenced by setCamera(), and updatePosition().
std::vector<CItem*> CTrolley::itemList
Definition at line 35 of file Trolley.h.
The documentation for this class was generated from the following files:
MyGraphics/Source/Trolley.h
MyGraphics/Source/Trolley.cpp