My Application: SP2 Class Reference
SP2 Class Reference
Stores the Enums, Functions, parameters and variables for SP2.cpp.
#include <SP2.h>
Public Types
enum KEYPRESS {
K_ENTER_CAR, K_EXIT_CAR, K_ENTER_TROLLEY, K_EXIT_TROLLEY,
K_LEFT_PICK, K_LEFT_PLACE, K_RIGHT_PICK, K_RIGHT_PLACE,
K_ENTER_CAM, K_EXIT_CAM, K_FIRST_FLOOR, K_SECOND_FLOOR,
K_START_STORY, K_TALK, NUM_KEYPRESS
}
enum GEOMETRY_TYPE {
GEO_AXES, GEO_TEXT, GEO_OUTER_FRONT, GEO_OUTER_BACK,
GEO_OUTER_LEFT, GEO_OUTER_RIGHT, GEO_OUTER_TOP, GEO_OUTER_BOTTOM,
GEO_CAR, GEO_CAR_TYRE, GEO_CAR_SCREEN, GEO_SUPERMARKET,
GEO_SUPERMARKET_WALL, GEO_SUPERMARKET_CEILING, GEO_SUPERMARKET_DOOR, GEO_PATCH,
GEO_CASHIER_TABLE, GEO_SECURITY_CAMERA, GEO_SECURITY_CAMERA_SCREEN, GEO_SHELF,
GEO_DISPLAY1, GEO_DISPLAY2, GEO_DISPLAY3, GEO_DISPLAY4,
GEO_TROLLEY, GEO_POTATO, GEO_BAG, GEO_THOR,
GEO_TARDIS, GEO_TARDIS_TOP, GEO_TARDIS_MID, GEO_TARDIS_SIGN,
GEO_TARDIS_BOT, GEO_WUKONG, GEO_ITEM, GEO_ITEM_1,
GEO_ITEM_2, GEO_ITEM_3, GEO_ITEM_4, GEO_ITEM_5,
GEO_ITEM_6, GEO_ITEM_7, GEO_ITEM_8, GEO_ITEM_9,
GEO_ITEM_10, GEO_INVENTORY_ITEM_1, GEO_INVENTORY_ITEM_2, GEO_INVENTORY_ITEM_3,
GEO_INVENTORY_ITEM_4, GEO_INVENTORY_ITEM_5, GEO_INVENTORY_ITEM_6, GEO_INVENTORY_ITEM_7,
GEO_INVENTORY_ITEM_8, GEO_INVENTORY_ITEM_9, GEO_INVENTORY_ITEM_10, GEO_HUMAN,
GEO_NON_MOVING_SHOPPER, GEO_NON_MOVING_SECURITYGUARD, GEO_HUMAN_SHOPPER_BODY, GEO_HUMAN_SHOPPER_ARM,
GEO_HUMAN_SHOPPER_HAND, GEO_HUMAN_SHOPPER_LEG, GEO_HUMAN_SECURITYGUARD_BODY, GEO_HUMAN_SECURITYGUARD_ARM,
GEO_HUMAN_SECURITYGUARD_HAND, GEO_HUMAN_SECURITYGUARD_LEG, GEO_HUMAN_STAFF_BODY, GEO_HUMAN_STAFF_ARM,
GEO_HUMAN_STAFF_HAND, GEO_HUMAN_STAFF_LEG, GEO_GAME3_BOB_BODY, GEO_GAME3_BOB_ARM,
GEO_GAME3_BOB_HAND, GEO_GAME3_BOB_LEG, GEO_CUBE, GEO_HAND,
GEO_MAP_1, GEO_MAP_2, GEO_MAP_PLAYER, NUM_GEOMETRY
}
enum UNIFORM_TYPE {
U_MVP = 0, U_MODELVIEW, U_MODELVIEW_INVERSE_TRANSPOSE, U_MATERIAL_AMBIENT,
U_MATERIAL_DIFFUSE, U_MATERIAL_SPECULAR, U_MATERIAL_SHININESS, U_LIGHT0_POSITION,
U_LIGHT0_COLOR, U_LIGHT0_POWER, U_LIGHT0_KC, U_LIGHT0_KL,
U_LIGHT0_KQ, U_LIGHTENABLED, U_LIGHT0_TYPE, U_LIGHT0_SPOTDIRECTION,
U_LIGHT0_COSCUTOFF, U_LIGHT0_COSINNER, U_LIGHT0_EXPONENT, U_NUMLIGHTS,
U_LIGHT1_POSITION, U_LIGHT1_COLOR, U_LIGHT1_POWER, U_LIGHT1_KC,
U_LIGHT1_KL, U_LIGHT1_KQ, U_LIGHT1_TYPE, U_LIGHT1_SPOTDIRECTION,
U_LIGHT1_COSCUTOFF, U_LIGHT1_COSINNER, U_LIGHT1_EXPONENT, U_COLOR_TEXTURE_ENABLED,
U_COLOR_TEXTURE, U_TEXT_ENABLED, U_TEXT_COLOR, U_TOTAL
}
Public Member Functions
SP2 ()
Default constructor.
~SP2 ()
Destructor.
virtual void Init ()
Init everything needed for the scene.
virtual void Update (double dt)
Update scene.
virtual void Render ()
Render everything in the scene.
virtual void Exit ()
Delete everything in objList and objList2.
Public Member Functions inherited from Scene
Scene ()
~Scene ()
Private Member Functions
void RenderMesh (Mesh *mesh, bool enableLight)
Render a mesh into the scene.
void RenderText (Mesh *mesh, std::string text, Color color)
Render test in world.
void RenderTextOnScreen (Mesh *mesh, std::string text, Color color, float size, float x, float y)
Render text on screen.
void Render2D (Mesh *mesh, float size, float x, float y)
Render in 2D.
void setLights ()
Light variables for all lights.
void getHandle ()
Get a handle for our "MVP" & "textColor" uniform.
void lightParameters ()
Passing uniform parameters.
void initValues ()
Init of misc values.
void initOuterSkybox ()
Generate skybox obj and texture and init values for skybox.
void renderOuterSkybox ()
Render outer skybox.
void renderText ()
Render all text on screen.
void initSuperMarket ()
Generate supermarket related obj and texture and create them on the first and second floor.
void updateSuperMarket (double dt)
Door and lift interaction within the supermarket.
void renderSuperMarket ()
Render supermarket doors.
void initCar ()
Generate car obj and texture and creating a car in scene.
void updateCar (double dt)
Update the current car that is being droved.
void renderCar ()
Render car.
void updateTrolley (double dt)
Update the trolley that is being pushed.
void initHuman (int type, Vector3 translation, Vector3 rotation, Vector3 camPosition, int radius)
Generate NPC obj and texture and creating them into the scene.
void updateHuman (double dt)
NPC movement.
void renderHuman ()
Render NPC.
void renderNonMovingShopper ()
Render non-moving shopper.
void renderNonMovingSecurityGuard ()
Render non-moving security guard.
void initItems ()
Generate and load all item obj and texture (2D and 3D)
void initSpecialItems ()
Generate obj and texture of items that will be placed on display cabinet.
void updateSpecialItems ()
void renderSpecialItems ()
Render items in display cabinet.
void initShelf (int Choice, Vector3 _translate, Vector3 _rotate)
Creates a shelf for floor 1.
void updateShelf ()
Check for interactions between player and shelf and updates it.
void renderShelf ()
Render shelf with its item.
void initCabinet ()
Generate display cabinet obj and texture.
void updateCabinet (double dt)
void renderCabinet ()
Render display cabinet.
void initCamera ()
Init security cameras and screens for security room.
void updateCamera (double dt)
Update security camera viewpoint.
void initHands ()
Init player's hand.
void updateHands (double dt)
Update transformation for hand when player moves.
void renderHands ()
Render player's hands.
void initPatch ()
Creates a wall patch for second floor.
void updatePatch ()
void renderPatch ()
void initGame ()
Init values for game.
void renderGame (int a)
Render game related obj.
void updateGame (double dt)
Update game.
bool updateBoundCheckGame3 ()
Bound check for game 3.
void renderInstruction (int a)
Render instructions for games.
void initMap ()
Init floor 1 map.
void renderMap ()
Render minimap and player's position.
void updateMap ()
Update character's position on minimap.
Private Attributes
unsigned m_vertexArrayID
Mesh * meshList [NUM_GEOMETRY]
unsigned m_programID
unsigned m_parameters [U_TOTAL]
Camera3 camera
Camera3 saved
MS modelStack
MS viewStack
MS projectionStack
Light lights [2]
bool aiTalk
float timer
bool togglelight
double fps
bool keypressed [NUM_KEYPRESS]
std::vector< CTrolley * > trolleyList
int floorNum
int newFloor
CObj * liftLeftDoor
CObj * liftRightDoor
float translateX
Vector3 supermarketSize
Vector3 supermarketPosition
Vector3 supermarketScale
Vector3 supermarketDoorMaxBound
Vector3 supermarketDoorMinBound
Vector3 supermarketSecurityDoorMaxBound
Vector3 supermarketSecurityDoorMinBound
float translateSecurityZ
std::vector< CItem * > checkoutList
Vector3 promoterMaxBound
Vector3 promoterMinBound
bool isTalking
Vector3 supermarketLiftSize
Vector3 supermarketLiftScale
Vector3 supermarketLiftPosition
Vector3 supermarketLiftMaxBound
Vector3 supermarketLiftMinBound
Vector3 supermarketLiftDoorMaxBound
Vector3 supermarketLiftDoorMinBound
bool disableLiftDoor
float translateLiftX
Vector3 outerSkyboxSize
Vector3 outerSkyboxMaxBound
Vector3 outerSkyboxMinBound
float skyboxOffset
std::vector< CObj * > objList
std::vector< CObj * > objList2
CObj * pObj
bool cam
int camNum
std::vector< CSecurityCamera * > cameraList
float rotateHandX
float rotateHandY
float trolleyRotateHandX
CObj * hands [2]
float tempX
float tempY
float tempZ
float tempPitch
float tempYaw
float tempTargetX
float tempTargetY
float tempTargetZ
float temp
CObj * tempP
float rotTardis
float tardisPitch
float tardisY
bool pressed
int playerScore [3]
float timeFrame
int inGame
bool displayInstruction
Vector3 game1MaxBound
Vector3 game1MinBound
bool pickCorrect
int randomItem
Vector3 game2MaxBound
Vector3 game2MinBound
int itemLeft
std::vector< CItem * > bagList
Vector3 game3MaxBound
Vector3 game3MinBound
float bobMoveX
float bobMoveZ
float tempBobMoveX
float tempBobMoveZ
bool game3
bool hitSomething
std::vector< CCharacter * > CharacterList
bool mainmenu
bool talk
double talkTimer
Vector3 mapMaxBound
Vector3 mapMinBound
float mapPositionX
float mapPositionZ
Detailed Description
Stores the Enums, Functions, parameters and variables for SP2.cpp.
Class SP2:
Definition at line 42 of file SP2.h.
Member Enumeration Documentation
enum SP2::GEOMETRY_TYPE
Enumerator
GEO_AXES
GEO_TEXT
GEO_OUTER_FRONT
GEO_OUTER_BACK
GEO_OUTER_LEFT
GEO_OUTER_RIGHT
GEO_OUTER_TOP
GEO_OUTER_BOTTOM
GEO_CAR
GEO_CAR_TYRE
GEO_CAR_SCREEN
GEO_SUPERMARKET
GEO_SUPERMARKET_WALL
GEO_SUPERMARKET_CEILING
GEO_SUPERMARKET_DOOR
GEO_PATCH
GEO_CASHIER_TABLE
GEO_SECURITY_CAMERA
GEO_SECURITY_CAMERA_SCREEN
GEO_SHELF
GEO_DISPLAY1
GEO_DISPLAY2
GEO_DISPLAY3
GEO_DISPLAY4
GEO_TROLLEY
GEO_POTATO
GEO_BAG
GEO_THOR
GEO_TARDIS
GEO_TARDIS_TOP
GEO_TARDIS_MID
GEO_TARDIS_SIGN
GEO_TARDIS_BOT
GEO_WUKONG
GEO_ITEM
GEO_ITEM_1
GEO_ITEM_2
GEO_ITEM_3
GEO_ITEM_4
GEO_ITEM_5
GEO_ITEM_6
GEO_ITEM_7
GEO_ITEM_8
GEO_ITEM_9
GEO_ITEM_10
GEO_INVENTORY_ITEM_1
GEO_INVENTORY_ITEM_2
GEO_INVENTORY_ITEM_3
GEO_INVENTORY_ITEM_4
GEO_INVENTORY_ITEM_5
GEO_INVENTORY_ITEM_6
GEO_INVENTORY_ITEM_7
GEO_INVENTORY_ITEM_8
GEO_INVENTORY_ITEM_9
GEO_INVENTORY_ITEM_10
GEO_HUMAN
GEO_NON_MOVING_SHOPPER
GEO_NON_MOVING_SECURITYGUARD
GEO_HUMAN_SHOPPER_BODY
GEO_HUMAN_SHOPPER_ARM
GEO_HUMAN_SHOPPER_HAND
GEO_HUMAN_SHOPPER_LEG
GEO_HUMAN_SECURITYGUARD_BODY
GEO_HUMAN_SECURITYGUARD_ARM
GEO_HUMAN_SECURITYGUARD_HAND
GEO_HUMAN_SECURITYGUARD_LEG
GEO_HUMAN_STAFF_BODY
GEO_HUMAN_STAFF_ARM
GEO_HUMAN_STAFF_HAND
GEO_HUMAN_STAFF_LEG
GEO_GAME3_BOB_BODY
GEO_GAME3_BOB_ARM
GEO_GAME3_BOB_HAND
GEO_GAME3_BOB_LEG
GEO_CUBE
GEO_HAND
GEO_MAP_1
GEO_MAP_2
GEO_MAP_PLAYER
NUM_GEOMETRY
Definition at line 63 of file SP2.h.
enum SP2::KEYPRESS
Enumerator
K_ENTER_CAR
K_EXIT_CAR
K_ENTER_TROLLEY
K_EXIT_TROLLEY
K_LEFT_PICK
K_LEFT_PLACE
K_RIGHT_PICK
K_RIGHT_PLACE
K_ENTER_CAM
K_EXIT_CAM
K_FIRST_FLOOR
K_SECOND_FLOOR
K_START_STORY
K_TALK
NUM_KEYPRESS
Definition at line 45 of file SP2.h.
enum SP2::UNIFORM_TYPE
Enumerator
U_MVP
U_MODELVIEW
U_MODELVIEW_INVERSE_TRANSPOSE
U_MATERIAL_AMBIENT
U_MATERIAL_DIFFUSE
U_MATERIAL_SPECULAR
U_MATERIAL_SHININESS
U_LIGHT0_POSITION
U_LIGHT0_COLOR
U_LIGHT0_POWER
U_LIGHT0_KC
U_LIGHT0_KL
U_LIGHT0_KQ
U_LIGHTENABLED
U_LIGHT0_TYPE
U_LIGHT0_SPOTDIRECTION
U_LIGHT0_COSCUTOFF
U_LIGHT0_COSINNER
U_LIGHT0_EXPONENT
U_NUMLIGHTS
U_LIGHT1_POSITION
U_LIGHT1_COLOR
U_LIGHT1_POWER
U_LIGHT1_KC
U_LIGHT1_KL
U_LIGHT1_KQ
U_LIGHT1_TYPE
U_LIGHT1_SPOTDIRECTION
U_LIGHT1_COSCUTOFF
U_LIGHT1_COSINNER
U_LIGHT1_EXPONENT
U_COLOR_TEXTURE_ENABLED
U_COLOR_TEXTURE
U_TEXT_ENABLED
U_TEXT_COLOR
U_TOTAL
Definition at line 168 of file SP2.h.
Constructor & Destructor Documentation
SP2::SP2 ()
Default constructor.
Definition at line 24 of file SP2.cpp.
SP2::~SP2 ()
Destructor.
Definition at line 34 of file SP2.cpp.
Member Function Documentation
void SP2::Exit () virtual
Delete everything in objList and objList2.
Implements Scene.
Definition at line 3233 of file SP2.cpp.
References m_programID, m_vertexArrayID, objList, and pObj.
void SP2::getHandle () private
Get a handle for our "MVP" & "textColor" uniform.
Definition at line 1017 of file SP2.cpp.
References m_parameters, m_programID, U_COLOR_TEXTURE, U_COLOR_TEXTURE_ENABLED, U_LIGHT0_COLOR, U_LIGHT0_COSCUTOFF, U_LIGHT0_COSINNER, U_LIGHT0_EXPONENT, U_LIGHT0_KC, U_LIGHT0_KL, U_LIGHT0_KQ, U_LIGHT0_POSITION, U_LIGHT0_POWER, U_LIGHT0_SPOTDIRECTION, U_LIGHT0_TYPE, U_LIGHT1_COLOR, U_LIGHT1_COSCUTOFF, U_LIGHT1_COSINNER, U_LIGHT1_EXPONENT, U_LIGHT1_KC, U_LIGHT1_KL, U_LIGHT1_KQ, U_LIGHT1_POSITION, U_LIGHT1_POWER, U_LIGHT1_SPOTDIRECTION, U_LIGHT1_TYPE, U_LIGHTENABLED, U_MATERIAL_AMBIENT, U_MATERIAL_DIFFUSE, U_MATERIAL_SHININESS, U_MATERIAL_SPECULAR, U_MODELVIEW, U_MODELVIEW_INVERSE_TRANSPOSE, U_MVP, U_NUMLIGHTS, U_TEXT_COLOR, and U_TEXT_ENABLED.
Referenced by Init().
void SP2::Init () virtual
Init everything needed for the scene.
Implements Scene.
Definition at line 44 of file SP2.cpp.
References CObj::calcBound(), camera, MeshBuilder::GenerateAxes(), MeshBuilder::GenerateOBJ(), MeshBuilder::GenerateText(), GEO_AXES, GEO_CUBE, GEO_NON_MOVING_SECURITYGUARD, GEO_NON_MOVING_SHOPPER, GEO_TEXT, getHandle(), Camera3::Init(), initCabinet(), initCamera(), initCar(), initGame(), initHands(), initHuman(), initMap(), initOuterSkybox(), initPatch(), initSpecialItems(), initSuperMarket(), initValues(), lightParameters(), MS::LoadMatrix(), LoadShaders(), LoadTGA(), m_programID, m_vertexArrayID, meshList, objList2, pObj, Camera::position, projectionStack, setLights(), Mtx44::SetToPerspective(), and Mesh::textureID.
void SP2::initCabinet () private
Generate display cabinet obj and texture.
Definition at line 494 of file SP2.cpp.
References CObj::calcBound(), MeshBuilder::GenerateOBJ(), GEO_DISPLAY1, GEO_DISPLAY2, GEO_DISPLAY3, GEO_DISPLAY4, LoadTGA(), meshList, objList2, pObj, rotTardis, supermarketPosition, supermarketScale, tardisPitch, tardisY, Mesh::textureID, Vector3::x, Vector3::y, and Vector3::z.
Referenced by Init().
void SP2::initCamera () private
Init security cameras and screens for security room.
Definition at line 173 of file SP2.cpp.
References CObj::calcBound(), cameraList, camNum, MeshBuilder::GenerateOBJ(), GEO_SECURITY_CAMERA, GEO_SECURITY_CAMERA_SCREEN, GEO_SUPERMARKET_DOOR, CObj::getTranslate(), LoadTGA(), meshList, objList2, pObj, Vector3::Set(), supermarketPosition, supermarketScale, supermarketSecurityDoorMaxBound, supermarketSecurityDoorMinBound, supermarketSize, Mesh::textureID, translateSecurityZ, Vector3::x, Vector3::y, and Vector3::z.
Referenced by Init().
void SP2::initCar () private
Generate car obj and texture and creating a car in scene.
Definition at line 463 of file SP2.cpp.
References CObj::calcBound(), MeshBuilder::GenerateOBJ(), MeshBuilder::GenerateQuad(), GEO_CAR, GEO_CAR_SCREEN, GEO_CAR_TYRE, Material::kAmbient, Material::kDiffuse, Material::kShininess, Material::kSpecular, LoadTGA(), Mesh::material, meshList, objList, pObj, Component::Set(), and Mesh::textureID.
Referenced by Init().
void SP2::initGame () private
Init values for game.
Definition at line 1200 of file SP2.cpp.
References bobMoveX, bobMoveZ, game1MaxBound, game1MinBound, game2MaxBound, game2MinBound, game3, game3MaxBound, game3MinBound, MeshBuilder::GenerateOBJ(), GEO_GAME3_BOB_ARM, GEO_GAME3_BOB_BODY, GEO_GAME3_BOB_HAND, GEO_GAME3_BOB_LEG, GEO_INVENTORY_ITEM_1, inGame, itemLeft, LoadTGA(), meshList, pickCorrect, playerScore, randomItem, Vector3::Set(), supermarketPosition, supermarketScale, Mesh::textureID, timeFrame, Vector3::x, Vector3::y, and Vector3::z.
Referenced by Init().
void SP2::initHands () private
Init player's hand.
Definition at line 159 of file SP2.cpp.
References MeshBuilder::GenerateOBJ(), GEO_HAND, hands, LoadTGA(), meshList, rotateHandX, rotateHandY, Mesh::textureID, and trolleyRotateHandX.
Referenced by Init().
void SP2::initHuman (int Choice, Vector3 translation, Vector3 rotation, Vector3 camPosition, int radius) private
Generate NPC obj and texture and creating them into the scene.
Parameters
Choice Determines what type of NPC
translation Position of the NPC
rotation Rotation of the NPC
camPosition NPC's camera position
radius The distance between player and NPC that allows interaction
Definition at line 852 of file SP2.cpp.
References CObj::calcBound(), camera, CharacterList, MeshBuilder::GenerateOBJ(), GEO_HUMAN, GEO_HUMAN_SECURITYGUARD_ARM, GEO_HUMAN_SECURITYGUARD_BODY, GEO_HUMAN_SECURITYGUARD_HAND, GEO_HUMAN_SECURITYGUARD_LEG, GEO_HUMAN_SHOPPER_ARM, GEO_HUMAN_SHOPPER_BODY, GEO_HUMAN_SHOPPER_HAND, GEO_HUMAN_SHOPPER_LEG, GEO_HUMAN_STAFF_ARM, GEO_HUMAN_STAFF_BODY, GEO_HUMAN_STAFF_HAND, GEO_HUMAN_STAFF_LEG, LoadTGA(), meshList, objList, objList2, pObj, Camera::position, and Mesh::textureID.
Referenced by Init().
void SP2::initItems () private
Generate and load all item obj and texture (2D and 3D)
Definition at line 393 of file SP2.cpp.
References MeshBuilder::GenerateOBJ(), MeshBuilder::GenerateQuad(), GEO_INVENTORY_ITEM_1, GEO_INVENTORY_ITEM_10, GEO_INVENTORY_ITEM_2, GEO_INVENTORY_ITEM_3, GEO_INVENTORY_ITEM_4, GEO_INVENTORY_ITEM_5, GEO_INVENTORY_ITEM_6, GEO_INVENTORY_ITEM_7, GEO_INVENTORY_ITEM_8, GEO_INVENTORY_ITEM_9, GEO_ITEM_1, GEO_ITEM_10, GEO_ITEM_2, GEO_ITEM_3, GEO_ITEM_4, GEO_ITEM_5, GEO_ITEM_6, GEO_ITEM_7, GEO_ITEM_8, GEO_ITEM_9, LoadTGA(), meshList, and Mesh::textureID.
Referenced by initSuperMarket().
void SP2::initMap () private
Init floor 1 map.
Definition at line 138 of file SP2.cpp.
References MeshBuilder::GenerateQuad(), GEO_MAP_1, GEO_MAP_2, GEO_MAP_PLAYER, LoadTGA(), mapMaxBound, mapMinBound, mapPositionX, mapPositionZ, meshList, Vector3::Set(), supermarketPosition, Mesh::textureID, Vector3::x, Vector3::y, and Vector3::z.
Referenced by Init().
void SP2::initOuterSkybox () private
Generate skybox obj and texture and init values for skybox.
Definition at line 1168 of file SP2.cpp.
References MeshBuilder::GenerateQuad(), GEO_OUTER_BACK, GEO_OUTER_BOTTOM, GEO_OUTER_FRONT, GEO_OUTER_LEFT, GEO_OUTER_RIGHT, GEO_OUTER_TOP, LoadTGA(), meshList, outerSkyboxMaxBound, outerSkyboxMinBound, outerSkyboxSize, Vector3::Set(), skyboxOffset, Mesh::textureID, Vector3::x, Vector3::y, and Vector3::z.
Referenced by Init().
void SP2::initPatch () private
Creates a wall patch for second floor.
Definition at line 941 of file SP2.cpp.
References CObj::calcBound(), MeshBuilder::GenerateOBJ(), GEO_PATCH, GEO_SUPERMARKET_WALL, CObj::getTranslate(), LoadTGA(), meshList, objList2, pObj, supermarketPosition, supermarketScale, supermarketSize, Mesh::textureID, Vector3::x, Vector3::y, and Vector3::z.
Referenced by Init().
void SP2::initShelf (int Choice, Vector3 _translate, Vector3 _rotate) private
Creates a shelf for floor 1.
Parameters
Choice A number from GEOMETRY_TYPE enum to specify an item to populate on the shelf
_translate Position to move from supermarket position
_rotate Rotation on the spot
Definition at line 244 of file SP2.cpp.
References CObj::calcBound(), GEO_ITEM, GEO_ITEM_1, GEO_ITEM_10, GEO_ITEM_2, GEO_ITEM_3, GEO_ITEM_4, GEO_ITEM_5, GEO_ITEM_6, GEO_ITEM_7, GEO_ITEM_8, GEO_ITEM_9, GEO_SHELF, CObj::getTranslate(), meshList, objList, pObj, and supermarketPosition.
Referenced by initSuperMarket().
void SP2::initSpecialItems () private
Generate obj and texture of items that will be placed on display cabinet.
Definition at line 531 of file SP2.cpp.
References MeshBuilder::GenerateOBJ(), GEO_POTATO, GEO_TARDIS_BOT, GEO_TARDIS_MID, GEO_TARDIS_SIGN, GEO_TARDIS_TOP, GEO_THOR, GEO_WUKONG, LoadTGA(), meshList, objList2, pObj, supermarketPosition, supermarketScale, Mesh::textureID, Vector3::x, Vector3::y, and Vector3::z.
Referenced by Init().
void SP2::initSuperMarket () private
Generate supermarket related obj and texture and create them on the first and second floor.
Definition at line 584 of file SP2.cpp.
References CObj::calcBound(), disableLiftDoor, MeshBuilder::GenerateOBJ(), GEO_BAG, GEO_CASHIER_TABLE, GEO_ITEM_1, GEO_ITEM_10, GEO_ITEM_2, GEO_ITEM_3, GEO_ITEM_4, GEO_ITEM_5, GEO_ITEM_6, GEO_ITEM_7, GEO_ITEM_8, GEO_ITEM_9, GEO_SECURITY_CAMERA, GEO_SHELF, GEO_SUPERMARKET, GEO_SUPERMARKET_CEILING, GEO_SUPERMARKET_DOOR, GEO_SUPERMARKET_WALL, GEO_TROLLEY, initItems(), initShelf(), liftLeftDoor, liftRightDoor, LoadTGA(), meshList, objList, objList2, pObj, Vector3::Set(), supermarketDoorMaxBound, supermarketDoorMinBound, supermarketLiftDoorMaxBound, supermarketLiftDoorMinBound, supermarketLiftMaxBound, supermarketLiftMinBound, supermarketLiftPosition, supermarketLiftScale, supermarketLiftSize, supermarketPosition, supermarketScale, supermarketSize, Mesh::textureID, translateLiftX, translateX, trolleyList, Vector3::x, Vector3::y, and Vector3::z.
Referenced by Init().
void SP2::initValues () private
Init of misc values.
Definition at line 1098 of file SP2.cpp.
References aiTalk, cam, floorNum, fps, GEO_HUMAN, keypressed, mainmenu, newFloor, NUM_KEYPRESS, objList, talk, talkTimer, timer, and togglelight.
Referenced by Init().
void SP2::lightParameters () private
Passing uniform parameters.
Definition at line 1067 of file SP2.cpp.
References lights, m_parameters, U_LIGHT0_COLOR, U_LIGHT0_COSCUTOFF, U_LIGHT0_COSINNER, U_LIGHT0_EXPONENT, U_LIGHT0_KC, U_LIGHT0_KL, U_LIGHT0_KQ, U_LIGHT0_POWER, U_LIGHT0_TYPE, U_LIGHT1_COLOR, U_LIGHT1_COSCUTOFF, U_LIGHT1_COSINNER, U_LIGHT1_EXPONENT, U_LIGHT1_KC, U_LIGHT1_KL, U_LIGHT1_KQ, U_LIGHT1_POWER, and U_LIGHT1_TYPE.
Referenced by Init().
void SP2::Render () virtual
Render everything in the scene.
Implements Scene.
Definition at line 2120 of file SP2.cpp.
References camera, floorNum, GEO_AXES, GEO_CAR, GEO_CAR_SCREEN, GEO_HUMAN, GEO_INVENTORY_ITEM_1, GEO_INVENTORY_ITEM_10, GEO_INVENTORY_ITEM_2, GEO_INVENTORY_ITEM_3, GEO_INVENTORY_ITEM_4, GEO_INVENTORY_ITEM_5, GEO_INVENTORY_ITEM_6, GEO_INVENTORY_ITEM_7, GEO_INVENTORY_ITEM_8, GEO_INVENTORY_ITEM_9, GEO_ITEM, GEO_ITEM_1, GEO_ITEM_10, GEO_ITEM_2, GEO_ITEM_3, GEO_ITEM_4, GEO_ITEM_5, GEO_ITEM_6, GEO_ITEM_7, GEO_ITEM_8, GEO_ITEM_9, GEO_NON_MOVING_SECURITYGUARD, GEO_NON_MOVING_SHOPPER, GEO_SHELF, GEO_SUPERMARKET_WALL, GEO_TEXT, GEO_TROLLEY, CObj::getID(), CObj::getRender(), CObj::getRotate(), CObj::getScale(), CObj::getSize(), CObj::getTranslate(), hands, inGame, MS::LoadIdentity(), MS::LookAt(), mainmenu, meshList, modelStack, objList, objList2, pObj, MS::PopMatrix(), Camera::position, MS::PushMatrix(), Render2D(), renderCar(), renderGame(), renderHands(), renderHuman(), renderInstruction(), renderMap(), RenderMesh(), renderNonMovingSecurityGuard(), renderNonMovingShopper(), renderOuterSkybox(), renderShelf(), renderSuperMarket(), RenderText(), renderText(), RenderTextOnScreen(), MS::Rotate(), MS::Scale(), Camera::target, togglelight, MS::Translate(), trolleyList, Camera::up, viewStack, Vector3::x, Vector3::y, and Vector3::z.
void SP2::Render2D (Mesh * mesh, float size, float x, float y) private
Render in 2D.
Parameters
mesh Mesh to be rendered
size Size of mesh
x Position of mesh along x axis
y Position of mesh along y axis
Definition at line 3409 of file SP2.cpp.
References Mtx44::a, MS::LoadIdentity(), MS::LoadMatrix(), m_parameters, modelStack, MS::PopMatrix(), projectionStack, MS::PushMatrix(), Mesh::Render(), MS::Scale(), Mtx44::SetToOrtho(), Mesh::textureID, MS::Top(), MS::Translate(), U_COLOR_TEXTURE, U_COLOR_TEXTURE_ENABLED, U_LIGHTENABLED, U_MVP, and viewStack.
Referenced by Render(), renderGame(), and renderMap().
void SP2::renderCabinet () private
Render display cabinet.
Definition at line 2453 of file SP2.cpp.
References GEO_DISPLAY1, GEO_DISPLAY2, GEO_DISPLAY3, GEO_DISPLAY4, CObj::getScale(), CObj::getTranslate(), meshList, modelStack, pObj, MS::PopMatrix(), MS::PushMatrix(), RenderMesh(), MS::Scale(), togglelight, MS::Translate(), Vector3::x, Vector3::y, and Vector3::z.
void SP2::renderCar () private
Render car.
Definition at line 2636 of file SP2.cpp.
References GEO_CAR, GEO_CAR_TYRE, CObj::getRotate(), CObj::getScale(), CObj::getTranslate(), meshList, modelStack, pObj, MS::PopMatrix(), MS::PushMatrix(), RenderMesh(), MS::Rotate(), MS::Scale(), togglelight, MS::Translate(), Vector3::x, Vector3::y, and Vector3::z.
Referenced by Render().
void SP2::renderGame (int a) private
Render game related obj.
Definition at line 2667 of file SP2.cpp.
References bobMoveX, bobMoveZ, camera, checkoutList, floorNum, game1MaxBound, game2MaxBound, game3MaxBound, GEO_GAME3_BOB_ARM, GEO_GAME3_BOB_BODY, GEO_GAME3_BOB_HAND, GEO_GAME3_BOB_LEG, GEO_INVENTORY_ITEM_1, GEO_TEXT, itemLeft, meshList, modelStack, pickCorrect, playerScore, MS::PopMatrix(), Camera::position, MS::PushMatrix(), randomItem, Render2D(), RenderMesh(), RenderText(), RenderTextOnScreen(), MS::Scale(), supermarketPosition, supermarketScale, timeFrame, togglelight, MS::Translate(), Vector3::x, Vector3::y, and Vector3::z.
Referenced by Render().
void SP2::renderHands () private
Render player's hands.
Definition at line 2412 of file SP2.cpp.
References cam, camera, GEO_HAND, meshList, modelStack, MS::PopMatrix(), Camera::position, MS::PushMatrix(), RenderMesh(), MS::Rotate(), rotateHandX, rotateHandY, MS::Scale(), togglelight, MS::Translate(), Vector3::x, Vector3::y, and Vector3::z.
Referenced by Render().
void SP2::renderHuman () private
Render NPC.
Definition at line 2960 of file SP2.cpp.
References GEO_HUMAN_SECURITYGUARD_ARM, GEO_HUMAN_SECURITYGUARD_BODY, GEO_HUMAN_SECURITYGUARD_HAND, GEO_HUMAN_SECURITYGUARD_LEG, GEO_HUMAN_SHOPPER_ARM, GEO_HUMAN_SHOPPER_BODY, GEO_HUMAN_SHOPPER_HAND, GEO_HUMAN_SHOPPER_LEG, GEO_HUMAN_STAFF_ARM, GEO_HUMAN_STAFF_BODY, GEO_HUMAN_STAFF_HAND, GEO_HUMAN_STAFF_LEG, CObj::getRotate(), CObj::getScale(), CObj::getTranslate(), meshList, modelStack, pObj, MS::PopMatrix(), MS::PushMatrix(), RenderMesh(), MS::Rotate(), MS::Scale(), togglelight, MS::Translate(), Vector3::x, Vector3::y, and Vector3::z.
Referenced by Render().
void SP2::renderInstruction (int a) private
Render instructions for games.
Definition at line 2801 of file SP2.cpp.
References displayInstruction, GEO_TEXT, meshList, and RenderTextOnScreen().
Referenced by Render().
void SP2::renderMap () private
Render minimap and player's position.
Definition at line 2377 of file SP2.cpp.
References floorNum, GEO_MAP_1, GEO_MAP_2, GEO_MAP_PLAYER, mapPositionX, mapPositionZ, meshList, and Render2D().
Referenced by Render().
void SP2::RenderMesh (Mesh * mesh, bool enableLight) private
Render a mesh into the scene.
Parameters
mesh The mesh to be rendered
enableLight Render with or without lights
Definition at line 3256 of file SP2.cpp.
References Mtx44::a, Mtx44::GetInverse(), Mtx44::GetTranspose(), Material::kAmbient, Material::kDiffuse, Material::kShininess, Material::kSpecular, m_parameters, Mesh::material, modelStack, projectionStack, Component::r, Mesh::Render(), Mesh::textureID, MS::Top(), U_COLOR_TEXTURE, U_COLOR_TEXTURE_ENABLED, U_LIGHTENABLED, U_MATERIAL_AMBIENT, U_MATERIAL_DIFFUSE, U_MATERIAL_SHININESS, U_MATERIAL_SPECULAR, U_MODELVIEW, U_MODELVIEW_INVERSE_TRANSPOSE, U_MVP, and viewStack.
Referenced by Render(), renderCabinet(), renderCar(), renderGame(), renderHands(), renderHuman(), renderNonMovingSecurityGuard(), renderNonMovingShopper(), renderOuterSkybox(), renderShelf(), renderSpecialItems(), and renderSuperMarket().
void SP2::renderNonMovingSecurityGuard () private
Render non-moving security guard.
Definition at line 2840 of file SP2.cpp.
References GEO_HUMAN_SECURITYGUARD_ARM, GEO_HUMAN_SECURITYGUARD_BODY, GEO_HUMAN_SECURITYGUARD_HAND, GEO_HUMAN_SECURITYGUARD_LEG, CObj::getRotate(), CObj::getScale(), CObj::getTranslate(), meshList, modelStack, pObj, MS::PopMatrix(), MS::PushMatrix(), RenderMesh(), MS::Rotate(), MS::Scale(), togglelight, MS::Translate(), Vector3::x, Vector3::y, and Vector3::z.
Referenced by Render().
void SP2::renderNonMovingShopper () private
Render non-moving shopper.
Definition at line 2899 of file SP2.cpp.
References GEO_HUMAN_SHOPPER_ARM, GEO_HUMAN_SHOPPER_BODY, GEO_HUMAN_SHOPPER_HAND, GEO_HUMAN_SHOPPER_LEG, CObj::getRotate(), CObj::getScale(), CObj::getTranslate(), meshList, modelStack, pObj, MS::PopMatrix(), MS::PushMatrix(), RenderMesh(), MS::Rotate(), MS::Scale(), togglelight, MS::Translate(), Vector3::x, Vector3::y, and Vector3::z.
Referenced by Render().
void SP2::renderOuterSkybox () private
Render outer skybox.
Definition at line 3182 of file SP2.cpp.
References GEO_OUTER_BACK, GEO_OUTER_BOTTOM, GEO_OUTER_FRONT, GEO_OUTER_LEFT, GEO_OUTER_RIGHT, GEO_OUTER_TOP, meshList, modelStack, outerSkyboxSize, MS::PopMatrix(), MS::PushMatrix(), RenderMesh(), MS::Rotate(), MS::Scale(), skyboxOffset, togglelight, MS::Translate(), Vector3::x, Vector3::y, and Vector3::z.
Referenced by Render().
void SP2::renderPatch () private
void SP2::renderShelf () private
Render shelf with its item.
Definition at line 2551 of file SP2.cpp.
References GEO_SHELF, CItem::getItem(), CObj::getRotate(), CObj::getScale(), CObj::getTranslate(), meshList, modelStack, pObj, MS::PopMatrix(), MS::PushMatrix(), RenderMesh(), MS::Rotate(), MS::Scale(), togglelight, MS::Translate(), Vector3::x, Vector3::y, and Vector3::z.
Referenced by Render().
void SP2::renderSpecialItems () private
Render items in display cabinet.
Definition at line 2487 of file SP2.cpp.
References GEO_POTATO, GEO_TARDIS_BOT, GEO_TARDIS_MID, GEO_TARDIS_SIGN, GEO_TARDIS_TOP, GEO_THOR, GEO_WUKONG, CObj::getScale(), CObj::getTranslate(), meshList, modelStack, pObj, MS::PopMatrix(), MS::PushMatrix(), RenderMesh(), MS::Rotate(), rotTardis, MS::Scale(), togglelight, MS::Translate(), Vector3::x, Vector3::y, and Vector3::z.
void SP2::renderSuperMarket () private
Render supermarket doors.
Definition at line 2592 of file SP2.cpp.
References floorNum, GEO_SUPERMARKET, GEO_SUPERMARKET_DOOR, meshList, modelStack, MS::PopMatrix(), MS::PushMatrix(), RenderMesh(), MS::Rotate(), MS::Scale(), supermarketPosition, supermarketScale, togglelight, MS::Translate(), translateSecurityZ, translateX, Vector3::x, Vector3::y, and Vector3::z.
Referenced by Render().
void SP2::RenderText (Mesh * mesh, std::string text, Color color) private
Render test in world.
Parameters
mesh Text's mesh
text Text to be rendered
color Color of the text
Definition at line 3310 of file SP2.cpp.
References Mtx44::a, m_parameters, modelStack, projectionStack, Color::r, Mesh::Render(), Mtx44::SetToTranslation(), Mesh::textureID, MS::Top(), U_COLOR_TEXTURE, U_COLOR_TEXTURE_ENABLED, U_LIGHTENABLED, U_MVP, U_TEXT_COLOR, U_TEXT_ENABLED, and viewStack.
Referenced by Render(), and renderGame().
void SP2::renderText () private
Render all text on screen.
Definition at line 2392 of file SP2.cpp.
References fps, GEO_TEXT, meshList, RenderTextOnScreen(), and talk.
Referenced by Render().
void SP2::RenderTextOnScreen (Mesh * mesh, std::string text, Color color, float size, float x, float y) private
Render text on screen.
Parameters
Text's mesh
text Text to be rendered
color Color for text
size Size of the text
x Position of text along x axis
y Position of text along y axis
Definition at line 3355 of file SP2.cpp.
References Mtx44::a, MS::LoadIdentity(), MS::LoadMatrix(), m_parameters, modelStack, MS::PopMatrix(), projectionStack, MS::PushMatrix(), Color::r, Mesh::Render(), MS::Scale(), Mtx44::SetToOrtho(), Mtx44::SetToTranslation(), Mesh::textureID, MS::Top(), MS::Translate(), U_COLOR_TEXTURE, U_COLOR_TEXTURE_ENABLED, U_LIGHTENABLED, U_MVP, U_TEXT_COLOR, U_TEXT_ENABLED, and viewStack.
Referenced by Render(), renderGame(), renderInstruction(), and renderText().
void SP2::setLights () private
Light variables for all lights.
Definition at line 984 of file SP2.cpp.
References Light::color, Light::cosCutoff, Light::cosInner, Math::DegreeToRadian(), Light::exponent, Light::kC, Light::kL, Light::kQ, Light::LIGHT_DIRECTIONAL, lights, Light::position, Light::power, Vector3::Set(), Position::Set(), Color::Set(), Light::spotDirection, and Light::type.
Referenced by Init().
void SP2::Update (double dt) virtual
Update scene.
Parameters
dt Time since previous update call
Implements Scene.
Definition at line 1249 of file SP2.cpp.
References bagList, cam, camera, camNum, CharacterList, checkoutList, displayInstruction, floorNum, fps, GEO_BAG, GEO_CAR, GEO_CASHIER_TABLE, GEO_HUMAN, GEO_ITEM, GEO_NON_MOVING_SECURITYGUARD, GEO_NON_MOVING_SHOPPER, GEO_SECURITY_CAMERA_SCREEN, GEO_SHELF, GEO_TROLLEY, CObj::getID(), CObj::getMaxBound(), CObj::getMinBound(), CObj::getRender(), hands, inGame, Application::IsKeyPressed(), itemLeft, K_ENTER_CAM, K_ENTER_CAR, K_ENTER_TROLLEY, K_EXIT_CAM, K_EXIT_CAR, K_EXIT_TROLLEY, K_FIRST_FLOOR, K_LEFT_PICK, K_LEFT_PLACE, K_RIGHT_PICK, K_RIGHT_PLACE, K_SECOND_FLOOR, K_START_STORY, K_TALK, keypressed, mainmenu, mapMaxBound, mapMinBound, meshList, objList, objList2, pickCorrect, pObj, Camera::position, randomItem, rotateHandX, rotateHandY, saved, CObj::setRender(), talk, talkTimer, Camera::target, togglelight, trolleyRotateHandX, updateCamera(), updateCar(), updateGame(), updateHands(), updateHuman(), updateMap(), updateShelf(), updateSuperMarket(), updateTrolley(), Vector3::x, Vector3::y, and Vector3::z.
bool SP2::updateBoundCheckGame3 () private
Bound check for game 3.
Definition at line 1708 of file SP2.cpp.
References bobMoveX, bobMoveZ, CObj::getMaxBound(), CObj::getMinBound(), CObj::getRender(), objList, pObj, Vector3::x, and Vector3::z.
Referenced by updateGame().
void SP2::updateCabinet (double dt) private
void SP2::updateCamera (double dt) private
Update security camera viewpoint.
Parameters
dt Time since previous update call
Definition at line 1513 of file SP2.cpp.
References cam, camera, cameraList, camNum, floorNum, game3, hands, Application::IsKeyPressed(), K_EXIT_CAM, keypressed, objList, objList2, outerSkyboxMaxBound, outerSkyboxMinBound, saved, and Camera3::Update().
Referenced by Update().
void SP2::updateCar (double dt) private
Update the current car that is being droved.
Parameters
dt Time since previous update call
Definition at line 1989 of file SP2.cpp.
References camera, CCar::carCamera, CObj::getRotate(), hands, Application::IsKeyPressed(), K_EXIT_CAR, keypressed, Vector3::Normalized(), Camera::position, rotateHandX, rotateHandY, saved, Vector3::Set(), Mtx44::SetToRotation(), Camera::target, Camera::up, and Vector3::y.
Referenced by Update().
void SP2::updateGame (double dt) private
Update game.
Parameters
dt Time since previous update call
Definition at line 1560 of file SP2.cpp.
References bobMoveX, bobMoveZ, cam, camera, checkoutList, floorNum, game1MaxBound, game1MinBound, game2MaxBound, game2MinBound, game3, game3MaxBound, game3MinBound, GEO_ITEM, GEO_ITEM_1, GEO_SHELF, CObj::getID(), inGame, Application::IsKeyPressed(), itemLeft, K_EXIT_CAM, K_START_STORY, keypressed, meshList, objList, playerScore, pObj, Camera::position, saved, tempBobMoveX, tempBobMoveZ, timeFrame, updateBoundCheckGame3(), Vector3::x, and Vector3::z.
Referenced by Update().
void SP2::updateHands (double dt) private
Update transformation for hand when player moves.
Parameters
dt Time since previous update call
Definition at line 1772 of file SP2.cpp.
References cam, GEO_CAR, GEO_TROLLEY, hands, Application::IsKeyPressed(), rotateHandX, and rotateHandY.
Referenced by Update().
void SP2::updateHuman (double dt) private
NPC movement.
Parameters
dt Time since previous update call
Definition at line 2029 of file SP2.cpp.
References camera, floorNum, GEO_HUMAN, objList, Camera::position, CObj::size, and WalkTo().
Referenced by Update().
void SP2::updateMap () private
Update character's position on minimap.
Definition at line 1499 of file SP2.cpp.
References camera, mapPositionX, mapPositionZ, Camera::position, supermarketScale, Vector3::x, and Vector3::z.
Referenced by Update().
void SP2::updatePatch () private
void SP2::updateShelf () private
Check for interactions between player and shelf and updates it.
Definition at line 1808 of file SP2.cpp.
References GEO_ITEM, hands, K_LEFT_PICK, K_LEFT_PLACE, K_RIGHT_PICK, K_RIGHT_PLACE, keypressed, pObj, CObj::setTranslate(), and CObj::size.
Referenced by Update().
void SP2::updateSpecialItems () private
void SP2::updateSuperMarket (double dt) private
Door and lift interaction within the supermarket.
Parameters
dt Time since previous update call
Definition at line 1849 of file SP2.cpp.
References CObj::calcBound(), camera, CharacterList, disableLiftDoor, floorNum, GEO_TROLLEY, CObj::getTranslate(), hands, K_FIRST_FLOOR, K_SECOND_FLOOR, keypressed, liftLeftDoor, liftRightDoor, newFloor, Camera::position, CObj::setTranslateX(), supermarketDoorMaxBound, supermarketDoorMinBound, supermarketLiftDoorMaxBound, supermarketLiftDoorMinBound, supermarketLiftMaxBound, supermarketLiftMinBound, supermarketScale, supermarketSecurityDoorMaxBound, supermarketSecurityDoorMinBound, translateLiftX, translateSecurityZ, translateX, Vector3::x, and Vector3::z.
Referenced by Update().
void SP2::updateTrolley (double dt) private
Update the trolley that is being pushed.
Parameters
dt Time since previous update call
Definition at line 1732 of file SP2.cpp.
References CObj::calcBound(), camera, CObj::getMaxBound(), CObj::getMinBound(), CObj::getRotate(), hands, K_EXIT_TROLLEY, keypressed, objList, outerSkyboxMaxBound, outerSkyboxMinBound, pObj, Camera::position, rotateHandX, rotateHandY, saved, Camera::target, trolleyRotateHandX, Camera::up, Vector3::x, Vector3::y, and Vector3::z.
Referenced by Update().
Field Documentation
bool SP2::aiTalk private
Definition at line 293 of file SP2.h.
Referenced by initValues().
std::vector<CItem*> SP2::bagList private
Definition at line 362 of file SP2.h.
Referenced by Update().
float SP2::bobMoveX private
Definition at line 366 of file SP2.h.
Referenced by initGame(), renderGame(), updateBoundCheckGame3(), and updateGame().
float SP2::bobMoveZ private
Definition at line 366 of file SP2.h.
Referenced by initGame(), renderGame(), updateBoundCheckGame3(), and updateGame().
bool SP2::cam private
Definition at line 331 of file SP2.h.
Referenced by initValues(), renderHands(), Update(), updateCamera(), updateGame(), and updateHands().
Camera3 SP2::camera private
Definition at line 225 of file SP2.h.
Referenced by Init(), initHuman(), Render(), renderGame(), renderHands(), Update(), updateCamera(), updateCar(), updateGame(), updateHuman(), updateMap(), updateSuperMarket(), and updateTrolley().
std::vector<CSecurityCamera*> SP2::cameraList private
Definition at line 333 of file SP2.h.
Referenced by initCamera(), and updateCamera().
int SP2::camNum private
Definition at line 332 of file SP2.h.
Referenced by initCamera(), Update(), and updateCamera().
std::vector<CCharacter*> SP2::CharacterList private
Definition at line 369 of file SP2.h.
Referenced by initHuman(), Update(), and updateSuperMarket().
std::vector<CItem*> SP2::checkoutList private
Definition at line 308 of file SP2.h.
Referenced by renderGame(), Update(), and updateGame().
bool SP2::disableLiftDoor private
Definition at line 318 of file SP2.h.
Referenced by initSuperMarket(), and updateSuperMarket().
bool SP2::displayInstruction private
Definition at line 352 of file SP2.h.
Referenced by renderInstruction(), and Update().
int SP2::floorNum private
Definition at line 302 of file SP2.h.
Referenced by initValues(), Render(), renderGame(), renderMap(), renderSuperMarket(), Update(), updateCamera(), updateGame(), updateHuman(), and updateSuperMarket().
double SP2::fps private
Definition at line 297 of file SP2.h.
Referenced by initValues(), renderText(), and Update().
Vector3 SP2::game1MaxBound private
Definition at line 355 of file SP2.h.
Referenced by initGame(), renderGame(), and updateGame().
Vector3 SP2::game1MinBound private
Definition at line 355 of file SP2.h.
Referenced by initGame(), and updateGame().
Vector3 SP2::game2MaxBound private
Definition at line 360 of file SP2.h.
Referenced by initGame(), renderGame(), and updateGame().
Vector3 SP2::game2MinBound private
Definition at line 360 of file SP2.h.
Referenced by initGame(), and updateGame().
bool SP2::game3 private
Definition at line 367 of file SP2.h.
Referenced by initGame(), updateCamera(), and updateGame().
Vector3 SP2::game3MaxBound private
Definition at line 365 of file SP2.h.
Referenced by initGame(), renderGame(), and updateGame().
Vector3 SP2::game3MinBound private
Definition at line 365 of file SP2.h.
Referenced by initGame(), and updateGame().
CObj* SP2::hands[2] private
Definition at line 337 of file SP2.h.
Referenced by initHands(), Render(), Update(), updateCamera(), updateCar(), updateHands(), updateShelf(), updateSuperMarket(), and updateTrolley().
bool SP2::hitSomething private
Definition at line 367 of file SP2.h.
int SP2::inGame private
Definition at line 351 of file SP2.h.
Referenced by initGame(), Render(), Update(), and updateGame().
bool SP2::isTalking private
Definition at line 314 of file SP2.h.
int SP2::itemLeft private
Definition at line 361 of file SP2.h.
Referenced by initGame(), renderGame(), Update(), and updateGame().
bool SP2::keypressed[NUM_KEYPRESS] private
Definition at line 298 of file SP2.h.
Referenced by initValues(), Update(), updateCamera(), updateCar(), updateGame(), updateShelf(), updateSuperMarket(), and updateTrolley().
CObj* SP2::liftLeftDoor private
Definition at line 303 of file SP2.h.
Referenced by initSuperMarket(), and updateSuperMarket().
CObj * SP2::liftRightDoor private
Definition at line 303 of file SP2.h.
Referenced by initSuperMarket(), and updateSuperMarket().
Light SP2::lights[2] private
Definition at line 227 of file SP2.h.
Referenced by lightParameters(), and setLights().
unsigned SP2::m_parameters[U_TOTAL] private
Definition at line 224 of file SP2.h.
Referenced by getHandle(), lightParameters(), Render2D(), RenderMesh(), RenderText(), and RenderTextOnScreen().
unsigned SP2::m_programID private
Definition at line 223 of file SP2.h.
Referenced by Exit(), getHandle(), and Init().
unsigned SP2::m_vertexArrayID private
Definition at line 221 of file SP2.h.
Referenced by Exit(), and Init().
bool SP2::mainmenu private
Definition at line 371 of file SP2.h.
Referenced by initValues(), Render(), and Update().
Vector3 SP2::mapMaxBound private
Definition at line 375 of file SP2.h.
Referenced by initMap(), and Update().
Vector3 SP2::mapMinBound private
Definition at line 375 of file SP2.h.
Referenced by initMap(), and Update().
float SP2::mapPositionX private
Definition at line 376 of file SP2.h.
Referenced by initMap(), renderMap(), and updateMap().
float SP2::mapPositionZ private
Definition at line 376 of file SP2.h.
Referenced by initMap(), renderMap(), and updateMap().
Mesh* SP2::meshList[NUM_GEOMETRY] private
Definition at line 222 of file SP2.h.
Referenced by Init(), initCabinet(), initCamera(), initCar(), initGame(), initHands(), initHuman(), initItems(), initMap(), initOuterSkybox(), initPatch(), initShelf(), initSpecialItems(), initSuperMarket(), Render(), renderCabinet(), renderCar(), renderGame(), renderHands(), renderHuman(), renderInstruction(), renderMap(), renderNonMovingSecurityGuard(), renderNonMovingShopper(), renderOuterSkybox(), renderShelf(), renderSpecialItems(), renderSuperMarket(), renderText(), Update(), and updateGame().
MS SP2::modelStack private
Definition at line 226 of file SP2.h.
Referenced by Render(), Render2D(), renderCabinet(), renderCar(), renderGame(), renderHands(), renderHuman(), RenderMesh(), renderNonMovingSecurityGuard(), renderNonMovingShopper(), renderOuterSkybox(), renderShelf(), renderSpecialItems(), renderSuperMarket(), RenderText(), and RenderTextOnScreen().
int SP2::newFloor private
Definition at line 302 of file SP2.h.
Referenced by initValues(), and updateSuperMarket().
std::vector<CObj*> SP2::objList private
Definition at line 326 of file SP2.h.
Referenced by Exit(), initCar(), initHuman(), initShelf(), initSuperMarket(), initValues(), Render(), Update(), updateBoundCheckGame3(), updateCamera(), updateGame(), updateHuman(), and updateTrolley().
std::vector<CObj*> SP2::objList2 private
Definition at line 327 of file SP2.h.
Referenced by Init(), initCabinet(), initCamera(), initHuman(), initPatch(), initSpecialItems(), initSuperMarket(), Render(), Update(), and updateCamera().
Vector3 SP2::outerSkyboxMaxBound private
Definition at line 322 of file SP2.h.
Referenced by initOuterSkybox(), updateCamera(), and updateTrolley().
Vector3 SP2::outerSkyboxMinBound private
Definition at line 322 of file SP2.h.
Referenced by initOuterSkybox(), updateCamera(), and updateTrolley().
Vector3 SP2::outerSkyboxSize private
Definition at line 322 of file SP2.h.
Referenced by initOuterSkybox(), and renderOuterSkybox().
bool SP2::pickCorrect private
Definition at line 356 of file SP2.h.
Referenced by initGame(), renderGame(), and Update().
int SP2::playerScore[3] private
Definition at line 349 of file SP2.h.
Referenced by initGame(), renderGame(), and updateGame().
CObj* SP2::pObj private
Definition at line 328 of file SP2.h.
Referenced by Exit(), Init(), initCabinet(), initCamera(), initCar(), initHuman(), initPatch(), initShelf(), initSpecialItems(), initSuperMarket(), Render(), renderCabinet(), renderCar(), renderHuman(), renderNonMovingSecurityGuard(), renderNonMovingShopper(), renderShelf(), renderSpecialItems(), Update(), updateBoundCheckGame3(), updateGame(), updateShelf(), and updateTrolley().
bool SP2::pressed private
Definition at line 347 of file SP2.h.
MS SP2::projectionStack private
Definition at line 226 of file SP2.h.
Referenced by Init(), Render2D(), RenderMesh(), RenderText(), and RenderTextOnScreen().
Vector3 SP2::promoterMaxBound private
Definition at line 311 of file SP2.h.
Vector3 SP2::promoterMinBound private
Definition at line 311 of file SP2.h.
int SP2::randomItem private
Definition at line 357 of file SP2.h.
Referenced by initGame(), renderGame(), and Update().
float SP2::rotateHandX private
Definition at line 336 of file SP2.h.
Referenced by initHands(), renderHands(), Update(), updateCar(), updateHands(), and updateTrolley().
float SP2::rotateHandY private
Definition at line 336 of file SP2.h.
Referenced by initHands(), renderHands(), Update(), updateCar(), updateHands(), and updateTrolley().
float SP2::rotTardis private
Definition at line 346 of file SP2.h.
Referenced by initCabinet(), and renderSpecialItems().
Camera3 SP2::saved private
Definition at line 225 of file SP2.h.
Referenced by Update(), updateCamera(), updateCar(), updateGame(), and updateTrolley().
float SP2::skyboxOffset private
Definition at line 323 of file SP2.h.
Referenced by initOuterSkybox(), and renderOuterSkybox().
Vector3 SP2::supermarketDoorMaxBound private
Definition at line 305 of file SP2.h.
Referenced by initSuperMarket(), and updateSuperMarket().
Vector3 SP2::supermarketDoorMinBound private
Definition at line 305 of file SP2.h.
Referenced by initSuperMarket(), and updateSuperMarket().
Vector3 SP2::supermarketLiftDoorMaxBound private
Definition at line 317 of file SP2.h.
Referenced by initSuperMarket(), and updateSuperMarket().
Vector3 SP2::supermarketLiftDoorMinBound private
Definition at line 317 of file SP2.h.
Referenced by initSuperMarket(), and updateSuperMarket().
Vector3 SP2::supermarketLiftMaxBound private
Definition at line 317 of file SP2.h.
Referenced by initSuperMarket(), and updateSuperMarket().
Vector3 SP2::supermarketLiftMinBound private
Definition at line 317 of file SP2.h.
Referenced by initSuperMarket(), and updateSuperMarket().
Vector3 SP2::supermarketLiftPosition private
Definition at line 316 of file SP2.h.
Referenced by initSuperMarket().
Vector3 SP2::supermarketLiftScale private
Definition at line 316 of file SP2.h.
Referenced by initSuperMarket().
Vector3 SP2::supermarketLiftSize private
Definition at line 316 of file SP2.h.
Referenced by initSuperMarket().
Vector3 SP2::supermarketPosition private
Definition at line 305 of file SP2.h.
Referenced by initCabinet(), initCamera(), initGame(), initMap(), initPatch(), initShelf(), initSpecialItems(), initSuperMarket(), renderGame(), and renderSuperMarket().
Vector3 SP2::supermarketScale private
Definition at line 305 of file SP2.h.
Referenced by initCabinet(), initCamera(), initGame(), initPatch(), initSpecialItems(), initSuperMarket(), renderGame(), renderSuperMarket(), updateMap(), and updateSuperMarket().
Vector3 SP2::supermarketSecurityDoorMaxBound private
Definition at line 306 of file SP2.h.
Referenced by initCamera(), and updateSuperMarket().
Vector3 SP2::supermarketSecurityDoorMinBound private
Definition at line 306 of file SP2.h.
Referenced by initCamera(), and updateSuperMarket().
Vector3 SP2::supermarketSize private
Definition at line 305 of file SP2.h.
Referenced by initCamera(), initPatch(), and initSuperMarket().
bool SP2::talk private
Definition at line 371 of file SP2.h.
Referenced by initValues(), renderText(), and Update().
double SP2::talkTimer private
Definition at line 372 of file SP2.h.
Referenced by initValues(), and Update().
float SP2::tardisPitch private
Definition at line 346 of file SP2.h.
Referenced by initCabinet().
float SP2::tardisY private
Definition at line 346 of file SP2.h.
Referenced by initCabinet().
float SP2::temp private
Definition at line 342 of file SP2.h.
float SP2::tempBobMoveX private
Definition at line 366 of file SP2.h.
Referenced by updateGame().
float SP2::tempBobMoveZ private
Definition at line 366 of file SP2.h.
Referenced by updateGame().
CObj* SP2::tempP private
Definition at line 343 of file SP2.h.
float SP2::tempPitch private
Definition at line 339 of file SP2.h.
float SP2::tempTargetX private
Definition at line 339 of file SP2.h.
float SP2::tempTargetY private
Definition at line 339 of file SP2.h.
float SP2::tempTargetZ private
Definition at line 339 of file SP2.h.
float SP2::tempX private
Definition at line 339 of file SP2.h.
float SP2::tempY private
Definition at line 339 of file SP2.h.
float SP2::tempYaw private
Definition at line 339 of file SP2.h.
float SP2::tempZ private
Definition at line 339 of file SP2.h.
float SP2::timeFrame private
Definition at line 350 of file SP2.h.
Referenced by initGame(), renderGame(), and updateGame().
float SP2::timer private
Definition at line 294 of file SP2.h.
Referenced by initValues().
bool SP2::togglelight private
Definition at line 296 of file SP2.h.
Referenced by initValues(), Render(), renderCabinet(), renderCar(), renderGame(), renderHands(), renderHuman(), renderNonMovingSecurityGuard(), renderNonMovingShopper(), renderOuterSkybox(), renderShelf(), renderSpecialItems(), renderSuperMarket(), and Update().
float SP2::translateLiftX private
Definition at line 319 of file SP2.h.
Referenced by initSuperMarket(), and updateSuperMarket().
float SP2::translateSecurityZ private
Definition at line 307 of file SP2.h.
Referenced by initCamera(), renderSuperMarket(), and updateSuperMarket().
float SP2::translateX private
Definition at line 304 of file SP2.h.
Referenced by initSuperMarket(), renderSuperMarket(), and updateSuperMarket().
std::vector<CTrolley*> SP2::trolleyList private
Definition at line 301 of file SP2.h.
Referenced by initSuperMarket(), and Render().
float SP2::trolleyRotateHandX private
Definition at line 336 of file SP2.h.
Referenced by initHands(), Update(), and updateTrolley().
MS SP2::viewStack private
Definition at line 226 of file SP2.h.
Referenced by Render(), Render2D(), RenderMesh(), RenderText(), and RenderTextOnScreen().
The documentation for this class was generated from the following files:
MyGraphics/Source/SP2.h
MyGraphics/Source/SP2.cpp