My Application: CCharacter Class Reference
CCharacter Class Reference
Defines default values of CCharacter's properties, (IsControlled, InteractionBound, Script, Role, moveX, moveZ, RouteID, MoveIsMax, Movement)
#include <Character.h>
Public Member Functions
void setMoveIsMax (bool MoveIsMax)
setting if legs can continue to move /param MoveIsMax - check if can continue to move
bool getMoveIsMax ()
return bool if cannot continue to move
void setMovement (int Movement)
set movement of NPC movement leg
int getMovement ()
return movement of NPC leg
void UpdateMovement (int Max)
update movement of NPC leg
CCharacter (void)
CCharacter default constructor.
void setRole (int Role)
Set role of the NPC.
int getRole ()
return the role of the NPC
void setInteractionBound (Vector3 Position, int Radius)
creates interaction bounds for NPC using NPC position and radius
bool getInteractionBound ()
returns if camera is in interaction bounds for NPC
void setScript (int choice)
sets the script of the NPC
int getScript ()
return the script phrases
virtual string updateScript ()
updates and change the script
void setmoveX (int moveX)
make the NPC move along the x aixs
int getmoveX ()
returns the number of units to move along X
void setmoveZ (int moveZ)
make the NPC move along the z aixs
int getmoveZ ()
returns the number of units to move along X
void setRouteID (int RouteID)
Sets the route for NPC.
int getRouteID ()
returns points of interest
Mesh * getCharacter ()
return character mesh pointer
void WalkTo (Vector3 TargetPosition, std::vector< CObj * > _objList)
makes the NPC move towards the target locations
~CCharacter (void)
CCharacter deconstructor.
Public Member Functions inherited from CObj
CObj (void)
Default constructor.
CObj (int _ID, Vector3 _translate, Vector3 _rotate, Vector3 _scale, Vector3 _size)
Overloaded constructor.
Vector3 getTranslate ()
return translate values
Vector3 getRotate ()
return rotate values
Vector3 getScale ()
return scale values
Vector3 getMaxBound ()
return maxBound values
Vector3 getMinBound ()
return minBound values
Vector3 getSize ()
return size values
int getID ()
return ID
bool getRender ()
return render state
void setRender (bool _render)
set render state
void setRotateY (float _rotateY)
set rotation on y axis
void setTranslateX (float _translateX)
set rotation on x axis
void setTranslate (Vector3 _translate)
set translation
virtual void calcBound ()
Calculates bound based on translate, size and scale.
virtual ~CObj (void)
Destructor.
Data Fields
vector< Vector3 > AiRouteLocation
Camera3 AICamera
Private Attributes
bool IsControlled
bool InteractionBound
int Script
Mesh * Character
int Role
int moveX
int moveZ
int RouteID
bool MoveIsMax
int Movement
Additional Inherited Members
Protected Attributes inherited from CObj
int ID
Vector3 translate
Vector3 rotate
Vector3 scale
Vector3 maxBound
Vector3 minBound
Vector3 size
bool render
Detailed Description
Defines default values of CCharacter's properties, (IsControlled, InteractionBound, Script, Role, moveX, moveZ, RouteID, MoveIsMax, Movement)
Class: CCharacter
Functions, (setMoveIsMax, getMoveIsMax, setMovement, getMovement, updateMovement, setIsControlled, getIsControlled, setRole, getRole, setInteractionBound, getInteractionBound, setScript, getScript, updateScript, setmoveX, getmoveX, setmoveZ, setRouteID, getRouteID, getCharacter, updateChar, WalkTo)
Vector (AiRouteLocation)
Definition at line 38 of file Character.h.
Constructor & Destructor Documentation
CCharacter::CCharacter (void)
CCharacter default constructor.
Definition at line 9 of file Character.cpp.
References IsControlled, setMoveIsMax(), and setMovement().
CCharacter::~CCharacter (void)
CCharacter deconstructor.
Definition at line 311 of file Character.cpp.
Member Function Documentation
Mesh * CCharacter::getCharacter ()
return character mesh pointer
Definition at line 163 of file Character.cpp.
References Character.
bool CCharacter::getInteractionBound ()
returns if camera is in interaction bounds for NPC
Definition at line 153 of file Character.cpp.
References InteractionBound.
Referenced by WalkTo().
bool CCharacter::getMoveIsMax ()
return bool if cannot continue to move
Definition at line 33 of file Character.cpp.
References MoveIsMax.
Referenced by UpdateMovement().
int CCharacter::getMovement ()
return movement of NPC leg
Definition at line 55 of file Character.cpp.
References Movement.
Referenced by UpdateMovement().
int CCharacter::getmoveX ()
returns the number of units to move along X
Definition at line 257 of file Character.cpp.
References moveX.
int CCharacter::getmoveZ ()
returns the number of units to move along X
Definition at line 279 of file Character.cpp.
References moveZ.
int CCharacter::getRole ()
return the role of the NPC
Definition at line 173 of file Character.cpp.
References Role.
int CCharacter::getRouteID ()
returns points of interest
Definition at line 301 of file Character.cpp.
References RouteID.
int CCharacter::getScript ()
return the script phrases
Definition at line 183 of file Character.cpp.
References Script.
Referenced by CCashier::updateScript(), CSecurityGuard::updateScript(), CShopper::updateScript(), CPromoter::updateScript(), and updateScript().
void CCharacter::setInteractionBound (Vector3 Position, int Radius)
creates interaction bounds for NPC using NPC position and radius
Parameters
Position - position of the NPC
Radius - the radius of the interaction bound from the NPC position
Definition at line 124 of file Character.cpp.
References CObj::getTranslate(), and InteractionBound.
Referenced by CCashier::CCashier(), CPromoter::CPromoter(), CSecurityGuard::CSecurityGuard(), and CShopper::CShopper().
void CCharacter::setMoveIsMax (bool MoveIsMax)
setting if legs can continue to move /param MoveIsMax - check if can continue to move
Definition at line 23 of file Character.cpp.
References MoveIsMax.
Referenced by CCharacter(), and UpdateMovement().
void CCharacter::setMovement (int Movement)
set movement of NPC movement leg
Parameters
Movement - see if moving
Definition at line 45 of file Character.cpp.
References Movement.
Referenced by CCharacter(), and UpdateMovement().
void CCharacter::setmoveX (int moveX)
make the NPC move along the x aixs
Parameters
moveX - amount of x units to move
Definition at line 247 of file Character.cpp.
References moveX.
void CCharacter::setmoveZ (int moveZ)
make the NPC move along the z aixs
Parameters
moveZ - amount of z units to move
Definition at line 269 of file Character.cpp.
References moveZ.
void CCharacter::setRole (int Role)
Set role of the NPC.
Parameters
Role using int to set roles
Definition at line 110 of file Character.cpp.
References Role.
Referenced by CCashier::CCashier(), CPromoter::CPromoter(), CSecurityGuard::CSecurityGuard(), and CShopper::CShopper().
void CCharacter::setRouteID (int RouteID)
Sets the route for NPC.
Parameters
RouteID - the points of interest to the NPC
Definition at line 291 of file Character.cpp.
References RouteID.
void CCharacter::setScript (int choice)
sets the script of the NPC
Parameters
Position - choice set which script the NPC is reading off
Definition at line 143 of file Character.cpp.
References Script.
void CCharacter::UpdateMovement (int Max)
update movement of NPC leg
Parameters
Max - check if leg has hit max angle
Definition at line 67 of file Character.cpp.
References getMoveIsMax(), getMovement(), Movement, setMoveIsMax(), and setMovement().
string CCharacter::updateScript () virtual
updates and change the script
Reimplemented in CPromoter, CShopper, CSecurityGuard, and CCashier.
Definition at line 193 of file Character.cpp.
References getScript().
void CCharacter::WalkTo (Vector3 TargetPos, std::vector< CObj * > _objList)
makes the NPC move towards the target locations
Parameters
TargetPos - the target the NPC is moving towards
_objList - the objects on the first floor
Definition at line 324 of file Character.cpp.
References CObj::calcBound(), CObj::getID(), getInteractionBound(), CObj::getMaxBound(), CObj::getMinBound(), CObj::getTranslate(), CObj::maxBound, CObj::minBound, CObj::setRotateY(), CObj::setTranslate(), Vector3::x, and Vector3::z.
Field Documentation
Camera3 CCharacter::AICamera
Definition at line 71 of file Character.h.
vector<Vector3> CCharacter::AiRouteLocation
Definition at line 54 of file Character.h.
Mesh* CCharacter::Character private
Definition at line 44 of file Character.h.
Referenced by getCharacter().
bool CCharacter::InteractionBound private
Definition at line 42 of file Character.h.
Referenced by getInteractionBound(), and setInteractionBound().
bool CCharacter::IsControlled private
Definition at line 41 of file Character.h.
Referenced by CCharacter().
bool CCharacter::MoveIsMax private
Definition at line 46 of file Character.h.
Referenced by getMoveIsMax(), and setMoveIsMax().
int CCharacter::Movement private
Definition at line 47 of file Character.h.
Referenced by getMovement(), setMovement(), and UpdateMovement().
int CCharacter::moveX private
Definition at line 45 of file Character.h.
Referenced by getmoveX(), and setmoveX().
int CCharacter::moveZ private
Definition at line 45 of file Character.h.
Referenced by getmoveZ(), and setmoveZ().
int CCharacter::Role private
Definition at line 45 of file Character.h.
Referenced by getRole(), and setRole().
int CCharacter::RouteID private
Definition at line 45 of file Character.h.
Referenced by getRouteID(), and setRouteID().
int CCharacter::Script private
Definition at line 43 of file Character.h.
Referenced by getScript(), and setScript().
The documentation for this class was generated from the following files:
MyGraphics/Source/Character.h
MyGraphics/Source/Character.cpp