My Application: Camera3 Class Reference
Camera3 Class Reference
Defines the default values of the Camera's properties (position, target, up, view) and its various states (Init, Update, Reset).
#include <Camera3.h>
Public Member Functions
Camera3 ()
Camera3's constructor.
~Camera3 ()
Camera3's destructor.
virtual void Init (const Vector3 &pos, const Vector3 &target, const Vector3 &up)
Initialize the various properties (position, target, up, view) and the rotation of Camera3.
virtual void Update (double dt, Vector3 &_outerSkyboxMaxBound, Vector3 &_outerSkyboxMinBound, std::vector< CObj * > &_objList, CObj **_hands, int floorNum, std::vector< CObj * > &_objList2)
Update the Camera's position, target, up and view location based on the time passed since the last update.
virtual void Reset ()
Reset the position, target, up and view coordinates and rotation to the default values.
bool boundCheck (Vector3 &_outerSkyboxMaxBound, Vector3 &_outerSkyboxMinBound, std::vector< CObj * > &_objList, CObj **_hands, int floorNum, std::vector< CObj * > &_objList2)
check for camera's bound and returning if camera has hit anything from any of the objects from objList and objList2
Public Member Functions inherited from Camera
Camera ()
Camera's constructor.
~Camera ()
Camera's destructor.
virtual void Update (double dt)
Update the Camera's position, target, up and view location based on the time passed since the last update.
Data Fields
Vector3 defaultPosition
Vector3 defaultTarget
Vector3 defaultUp
Vector3 defaultView
Mtx44 rotation
int current
Vector3 maxBound
Vector3 minBound
Data Fields inherited from Camera
Vector3 position
Vector3 target
Vector3 up
Vector3 view
Detailed Description
Defines the default values of the Camera's properties (position, target, up, view) and its various states (Init, Update, Reset).
Class Camera3:
Definition at line 24 of file Camera3.h.
Constructor & Destructor Documentation
Camera3::Camera3 ()
Camera3's constructor.
Definition at line 12 of file Camera3.cpp.
Camera3::~Camera3 ()
Camera3's destructor.
Definition at line 22 of file Camera3.cpp.
Member Function Documentation
bool Camera3::boundCheck (Vector3 & _outerSkyboxMaxBound, Vector3 & _outerSkyboxMinBound, std::vector< CObj * > & _objList, CObj ** _hands, int floorNum, std::vector< CObj * > & _objList2)
check for camera's bound and returning if camera has hit anything from any of the objects from objList and objList2
Parameters
&_outerSkyboxMaxBound - the maximum value of X and z of the skybox occupy
&_outerSkyboxMinBound - the minimum value of x and z of the skybox occupy
&_objList - the list of objects that is on first floor of supermarket in scene
**_hands used to check if player is using car or trolley
flooNum - which floor the camera is on
&_objList2 - the list of objects on 2nd floor
Definition at line 559 of file Camera3.cpp.
References current, CObj::getID(), CObj::getMaxBound(), CObj::getMinBound(), CObj::getRender(), maxBound, minBound, Camera::position, Vector3::x, Vector3::y, and Vector3::z.
Referenced by Update().
void Camera3::Init (const Vector3 & pos, const Vector3 & target, const Vector3 & up) virtual
Initialize the various properties (position, target, up, view) and the rotation of Camera3.
Parameters
pos the location of the camera.
target the location at which the camera is looking at.
up the vertically up vector that is perpendicular to the camera.
Reimplemented from Camera.
Definition at line 38 of file Camera3.cpp.
References Vector3::Cross(), defaultPosition, defaultTarget, defaultUp, defaultView, Vector3::Normalize(), Vector3::Normalized(), Camera::position, rotation, Mtx44::SetToIdentity(), Camera::target, Camera::view, and Vector3::y.
Referenced by SP2::Init().
void Camera3::Reset () virtual
Reset the position, target, up and view coordinates and rotation to the default values.
Reimplemented from Camera.
Definition at line 531 of file Camera3.cpp.
References defaultPosition, defaultTarget, defaultUp, defaultView, Camera::position, rotation, Mtx44::SetToIdentity(), Camera::target, Camera::up, and Camera::view.
Referenced by Update().
void Camera3::Update (double dt, Vector3 & _outerSkyboxMaxBound, Vector3 & _outerSkyboxMinBound, std::vector< CObj * > & _objList, CObj ** _hands, int floorNum, std::vector< CObj * > & _objList2) virtual
Update the Camera's position, target, up and view location based on the time passed since the last update.
Parameters
dt - the time passed since the last update.
Definition at line 58 of file Camera3.cpp.
References boundCheck(), CObj::calcBound(), Vector3::Cross(), current, CObj::getID(), CObj::getMaxBound(), CObj::getMinBound(), Application::IsKeyPressed(), maxBound, minBound, Vector3::Normalize(), Vector3::Normalized(), Camera::position, Math::RadianToDegree(), Reset(), rotation, CObj::setRotateY(), Mtx44::SetToRotation(), Camera::target, Camera::up, CTrolley::updatePosition(), Camera::view, Vector3::x, Vector3::y, and Vector3::z.
Referenced by SP2::updateCamera().
Field Documentation
int Camera3::current
Definition at line 33 of file Camera3.h.
Referenced by boundCheck(), and Update().
Vector3 Camera3::defaultPosition
Definition at line 27 of file Camera3.h.
Referenced by Init(), and Reset().
Vector3 Camera3::defaultTarget
Definition at line 28 of file Camera3.h.
Referenced by Init(), and Reset().
Vector3 Camera3::defaultUp
Definition at line 29 of file Camera3.h.
Referenced by Init(), and Reset().
Vector3 Camera3::defaultView
Definition at line 30 of file Camera3.h.
Referenced by Init(), and Reset().
Vector3 Camera3::maxBound
Definition at line 34 of file Camera3.h.
Referenced by boundCheck(), and Update().
Vector3 Camera3::minBound
Definition at line 34 of file Camera3.h.
Referenced by boundCheck(), and Update().
Mtx44 Camera3::rotation
Definition at line 32 of file Camera3.h.
Referenced by Init(), Reset(), and Update().
The documentation for this class was generated from the following files:
MyGraphics/Source/Camera3.h
MyGraphics/Source/Camera3.cpp