My Application: CPromoter Class Reference
CPromoter Class Reference
Defines functions (updateScript, InteractionBound)
#include <CPromoter.h>
Public Member Functions
CPromoter (void)
CPromoter default constructor.
CPromoter (int _ID, Vector3 _translate, Vector3 _rotate, Vector3 _scale, Vector3 _size, Vector3 camPosition, int radius)
CPromoter overloaded constructror.
string updateScript ()
returns the new script for the promoter NPC
bool InteractionBound (Vector3 Position)
returns if camera is within interaction bound of promoter
~CPromoter (void)
CPromoter deconstructor.
Public Member Functions inherited from CCharacter
void setMoveIsMax (bool MoveIsMax)
setting if legs can continue to move /param MoveIsMax - check if can continue to move
bool getMoveIsMax ()
return bool if cannot continue to move
void setMovement (int Movement)
set movement of NPC movement leg
int getMovement ()
return movement of NPC leg
void UpdateMovement (int Max)
update movement of NPC leg
CCharacter (void)
CCharacter default constructor.
void setRole (int Role)
Set role of the NPC.
int getRole ()
return the role of the NPC
void setInteractionBound (Vector3 Position, int Radius)
creates interaction bounds for NPC using NPC position and radius
bool getInteractionBound ()
returns if camera is in interaction bounds for NPC
void setScript (int choice)
sets the script of the NPC
int getScript ()
return the script phrases
void setmoveX (int moveX)
make the NPC move along the x aixs
int getmoveX ()
returns the number of units to move along X
void setmoveZ (int moveZ)
make the NPC move along the z aixs
int getmoveZ ()
returns the number of units to move along X
void setRouteID (int RouteID)
Sets the route for NPC.
int getRouteID ()
returns points of interest
Mesh * getCharacter ()
return character mesh pointer
void WalkTo (Vector3 TargetPosition, std::vector< CObj * > _objList)
makes the NPC move towards the target locations
~CCharacter (void)
CCharacter deconstructor.
Public Member Functions inherited from CObj
CObj (void)
Default constructor.
CObj (int _ID, Vector3 _translate, Vector3 _rotate, Vector3 _scale, Vector3 _size)
Overloaded constructor.
Vector3 getTranslate ()
return translate values
Vector3 getRotate ()
return rotate values
Vector3 getScale ()
return scale values
Vector3 getMaxBound ()
return maxBound values
Vector3 getMinBound ()
return minBound values
Vector3 getSize ()
return size values
int getID ()
return ID
bool getRender ()
return render state
void setRender (bool _render)
set render state
void setRotateY (float _rotateY)
set rotation on y axis
void setTranslateX (float _translateX)
set rotation on x axis
void setTranslate (Vector3 _translate)
set translation
virtual void calcBound ()
Calculates bound based on translate, size and scale.
virtual ~CObj (void)
Destructor.
Additional Inherited Members
Data Fields inherited from CCharacter
vector< Vector3 > AiRouteLocation
Camera3 AICamera
Protected Attributes inherited from CObj
int ID
Vector3 translate
Vector3 rotate
Vector3 scale
Vector3 maxBound
Vector3 minBound
Vector3 size
bool render
Detailed Description
Defines functions (updateScript, InteractionBound)
Class CPromoter:
Definition at line 25 of file CPromoter.h.
Constructor & Destructor Documentation
CPromoter::CPromoter (void)
CPromoter default constructor.
Definition at line 9 of file CPromoter.cpp.
CPromoter::CPromoter (int _ID, Vector3 _translate, Vector3 _rotate, Vector3 _scale, Vector3 _size, Vector3 camPosition, int radius)
CPromoter overloaded constructror.
Parameters
_ID ID for human in objList
_translate - translation of CPromoter
_rotate - rotation of promoter
_scale - scale of promoter
_size - the size of human object model camPosition - camera position from promoter
radius - the radius of the interaction bound for Promoter NPC
Definition at line 32 of file CPromoter.cpp.
References CObj::ID, CObj::rotate, CObj::scale, CCharacter::setInteractionBound(), CCharacter::setRole(), CObj::size, and CObj::translate.
CPromoter::~CPromoter (void)
CPromoter deconstructor.
Definition at line 123 of file CPromoter.cpp.
Member Function Documentation
bool CPromoter::InteractionBound (Vector3 Position)
returns if camera is within interaction bound of promoter
Parameters
Position - the position of the NPC
Definition at line 50 of file CPromoter.cpp.
string CPromoter::updateScript () virtual
returns the new script for the promoter NPC
Reimplemented from CCharacter.
Definition at line 60 of file CPromoter.cpp.
References CCharacter::getScript().
The documentation for this class was generated from the following files:
MyGraphics/Source/CPromoter.h
MyGraphics/Source/CPromoter.cpp