My Application: CObj Class Reference
CObj Class Reference
Stores Item Data.
#include <Obj.h>
Public Member Functions
CObj (void)
Default constructor.
CObj (int _ID, Vector3 _translate, Vector3 _rotate, Vector3 _scale, Vector3 _size)
Overloaded constructor.
Vector3 getTranslate ()
return translate values
Vector3 getRotate ()
return rotate values
Vector3 getScale ()
return scale values
Vector3 getMaxBound ()
return maxBound values
Vector3 getMinBound ()
return minBound values
Vector3 getSize ()
return size values
int getID ()
return ID
bool getRender ()
return render state
void setRender (bool _render)
set render state
void setRotateY (float _rotateY)
set rotation on y axis
void setTranslateX (float _translateX)
set rotation on x axis
void setTranslate (Vector3 _translate)
set translation
virtual void calcBound ()
Calculates bound based on translate, size and scale.
virtual ~CObj (void)
Destructor.
Protected Attributes
int ID
Vector3 translate
Vector3 rotate
Vector3 scale
Vector3 maxBound
Vector3 minBound
Vector3 size
bool render
Detailed Description
Stores Item Data.
Class CObj:
Definition at line 22 of file Obj.h.
Constructor & Destructor Documentation
CObj::CObj (void)
Default constructor.
Definition at line 9 of file Obj.cpp.
CObj::CObj (int _ID, Vector3 _translate, Vector3 _rotate, Vector3 _scale, Vector3 _size)
Overloaded constructor.
Definition at line 19 of file Obj.cpp.
CObj::~CObj (void) virtual
Destructor.
Definition at line 29 of file Obj.cpp.
Member Function Documentation
void CObj::calcBound () virtual
Calculates bound based on translate, size and scale.
Reimplemented in CItem, CShelf, CTrolley, and CCar.
Definition at line 130 of file Obj.cpp.
References maxBound, minBound, scale, Vector3::Set(), size, translate, Vector3::x, Vector3::y, and Vector3::z.
Referenced by SP2::Init(), SP2::initCabinet(), SP2::initCamera(), SP2::initCar(), SP2::initHuman(), SP2::initPatch(), SP2::initShelf(), SP2::initSuperMarket(), Camera3::Update(), SP2::updateSuperMarket(), SP2::updateTrolley(), and CCharacter::WalkTo().
int CObj::getID ()
return ID
Returns
ID similar to SP2::GEOMETRY_TYPE
Definition at line 119 of file Obj.cpp.
References ID.
Referenced by Camera3::boundCheck(), SP2::Render(), Camera3::Update(), SP2::Update(), SP2::updateGame(), and CCharacter::WalkTo().
Vector3 CObj::getMaxBound ()
return maxBound values
Returns
maxBound values
Definition at line 80 of file Obj.cpp.
References maxBound.
Referenced by Camera3::boundCheck(), Camera3::Update(), SP2::Update(), SP2::updateBoundCheckGame3(), SP2::updateTrolley(), and CCharacter::WalkTo().
Vector3 CObj::getMinBound ()
return minBound values
Returns
minBound values
Definition at line 93 of file Obj.cpp.
References minBound.
Referenced by Camera3::boundCheck(), Camera3::Update(), SP2::Update(), SP2::updateBoundCheckGame3(), SP2::updateTrolley(), and CCharacter::WalkTo().
bool CObj::getRender ()
return render state
Returns
render state
Definition at line 145 of file Obj.cpp.
References render.
Referenced by Camera3::boundCheck(), SP2::Render(), SP2::Update(), and SP2::updateBoundCheckGame3().
Vector3 CObj::getRotate ()
return rotate values
Returns
rotate values
Definition at line 54 of file Obj.cpp.
References rotate.
Referenced by SP2::Render(), SP2::renderCar(), SP2::renderHuman(), SP2::renderNonMovingSecurityGuard(), SP2::renderNonMovingShopper(), SP2::renderShelf(), SP2::updateCar(), and SP2::updateTrolley().
Vector3 CObj::getScale ()
return scale values
Returns
scale values
Definition at line 67 of file Obj.cpp.
References scale.
Referenced by SP2::Render(), SP2::renderCabinet(), SP2::renderCar(), SP2::renderHuman(), SP2::renderNonMovingSecurityGuard(), SP2::renderNonMovingShopper(), SP2::renderShelf(), and SP2::renderSpecialItems().
Vector3 CObj::getSize ()
return size values
Returns
size values
Definition at line 106 of file Obj.cpp.
References size.
Referenced by SP2::Render().
Vector3 CObj::getTranslate ()
return translate values
Returns
translate values
Definition at line 41 of file Obj.cpp.
References translate.
Referenced by SP2::initCamera(), SP2::initPatch(), SP2::initShelf(), SP2::Render(), SP2::renderCabinet(), SP2::renderCar(), SP2::renderHuman(), SP2::renderNonMovingSecurityGuard(), SP2::renderNonMovingShopper(), SP2::renderShelf(), SP2::renderSpecialItems(), CCharacter::setInteractionBound(), SP2::updateSuperMarket(), and CCharacter::WalkTo().
void CObj::setRender (bool _render)
set render state
Definition at line 156 of file Obj.cpp.
References render.
Referenced by SP2::Update().
void CObj::setRotateY (float _rotateY)
set rotation on y axis
Definition at line 167 of file Obj.cpp.
References rotate, and Vector3::y.
Referenced by Camera3::Update(), and CCharacter::WalkTo().
void CObj::setTranslate (Vector3 _translate)
set translation
Definition at line 189 of file Obj.cpp.
References translate.
Referenced by SP2::updateShelf(), and CCharacter::WalkTo().
void CObj::setTranslateX (float _translateX)
set rotation on x axis
Definition at line 178 of file Obj.cpp.
References translate, and Vector3::x.
Referenced by SP2::updateSuperMarket().
Field Documentation
int CObj::ID protected
Definition at line 38 of file Obj.h.
Referenced by CCashier::CCashier(), CPromoter::CPromoter(), CSecurityGuard::CSecurityGuard(), CShopper::CShopper(), and getID().
Vector3 CObj::maxBound protected
Definition at line 40 of file Obj.h.
Referenced by CCar::calcBound(), CTrolley::calcBound(), CShelf::calcBound(), calcBound(), CItem::calcBound(), getMaxBound(), and CCharacter::WalkTo().
Vector3 CObj::minBound protected
Definition at line 40 of file Obj.h.
Referenced by CCar::calcBound(), CTrolley::calcBound(), CShelf::calcBound(), calcBound(), CItem::calcBound(), getMinBound(), and CCharacter::WalkTo().
bool CObj::render protected
Definition at line 42 of file Obj.h.
Referenced by getRender(), and setRender().
Vector3 CObj::rotate protected
Definition at line 39 of file Obj.h.
Referenced by CCashier::CCashier(), CPromoter::CPromoter(), CSecurityGuard::CSecurityGuard(), CShopper::CShopper(), getRotate(), and setRotateY().
Vector3 CObj::scale protected
Definition at line 39 of file Obj.h.
Referenced by CCar::calcBound(), CTrolley::calcBound(), CShelf::calcBound(), calcBound(), CItem::calcBound(), CCashier::CCashier(), CPromoter::CPromoter(), CSecurityGuard::CSecurityGuard(), CShopper::CShopper(), getScale(), CTrolley::setCamera(), and CTrolley::updatePosition().
Vector3 CObj::size protected
Definition at line 41 of file Obj.h.
Referenced by CCar::calcBound(), CTrolley::calcBound(), CShelf::calcBound(), calcBound(), CItem::calcBound(), CCashier::CCashier(), CPromoter::CPromoter(), CSecurityGuard::CSecurityGuard(), CShopper::CShopper(), getSize(), CTrolley::setCamera(), SP2::updateHuman(), CTrolley::updatePosition(), and SP2::updateShelf().
Vector3 CObj::translate protected
Definition at line 39 of file Obj.h.
Referenced by CCar::calcBound(), CTrolley::calcBound(), CShelf::calcBound(), calcBound(), CItem::calcBound(), CCashier::CCashier(), CPromoter::CPromoter(), CSecurityGuard::CSecurityGuard(), CShopper::CShopper(), getTranslate(), CCar::setCamera(), CTrolley::setCamera(), setTranslate(), setTranslateX(), CCar::updatePosition(), and CTrolley::updatePosition().
The documentation for this class was generated from the following files:
MyGraphics/Source/Obj.h
MyGraphics/Source/Obj.cpp