My Application: MyGraphics/Source/LoadOBJ.h File Reference
LoadOBJ.h File Reference
Header file for LoadOBJ Class.
#include <vector>
#include "Vertex.h"
#include "Vector3.h"
Functions
bool LoadOBJ (const char *file_path, std::vector< Position > &out_vertices, std::vector< TexCoord > &out_uvs, std::vector< Vector3 > &out_normals)
void IndexVBO (std::vector< Position > &in_vertices, std::vector< TexCoord > &in_uvs, std::vector< Vector3 > &in_normals, std::vector< unsigned > &out_indices, std::vector< Vertex > &out_vertices)
Detailed Description
Header file for LoadOBJ Class.
Author
Team 8
Definition in file LoadOBJ.h.
Function Documentation
void IndexVBO (std::vector< Position > & in_vertices, std::vector< TexCoord > & in_uvs, std::vector< Vector3 > & in_normals, std::vector< unsigned > & out_indices, std::vector< Vertex > & out_vertices)
Definition at line 149 of file LoadOBJ.cpp.
References getSimilarVertexIndex_fast(), Vertex::pos, TexCoord::Set(), Position::Set(), and Vertex::texCoord.
Referenced by MeshBuilder::GenerateOBJ().
bool LoadOBJ (const char * file_path, std::vector< Position > & out_vertices, std::vector< TexCoord > & out_uvs, std::vector< Vector3 > & out_normals)
Definition at line 7 of file LoadOBJ.cpp.
References TexCoord::u, TexCoord::v, Vector3::x, Position::x, Vector3::y, Position::y, Vector3::z, and Position::z.
Referenced by MeshBuilder::GenerateOBJ().