My Application: TexCoord Struct Reference
TexCoord Struct Reference
sets texCoord for textures
#include <Vertex.h>
Public Member Functions
TexCoord (float u=0, float v=0)
void Set (float u, float v)
Data Fields
float u
float v
Detailed Description
sets texCoord for textures
struct TexCoord:
Definition at line 20 of file Vertex.h.
Constructor & Destructor Documentation
TexCoord::TexCoord (float u = 0, float v = 0) inline
Definition at line 23 of file Vertex.h.
References Set().
Member Function Documentation
void TexCoord::Set (float u, float v) inline
Definition at line 24 of file Vertex.h.
References u, and v.
Referenced by MeshBuilder::GenerateQuad(), MeshBuilder::GenerateText(), IndexVBO(), and TexCoord().
Field Documentation
float TexCoord::u
Definition at line 22 of file Vertex.h.
Referenced by MeshBuilder::GenerateQuad(), LoadOBJ(), and Set().
float TexCoord::v
Definition at line 22 of file Vertex.h.
Referenced by MeshBuilder::GenerateQuad(), LoadOBJ(), and Set().
The documentation for this struct was generated from the following file:
MyGraphics/Source/Vertex.h